### ISSUE TITLE
tendis docker container

### ISSUE THREAD

**Issue by jainal09** [Tencent/Tendis#10]
I was wondering is there any pre-built, docker container for running tendis?

**Comment by TendisDev** [comment]
The tendis official docker contianer would been released one week later.

**Comment by jainal09** [comment]
Cool, thanks for clarifying!

**Comment by OMG-By** [comment]
http://tendis.cn/#/Tendisplus/%E8%BF%90%E7%BB%B4/new_cluster_compose
