### ISSUE TITLE
建议增加关闭 binlog 的配置选项

### ISSUE THREAD

**Issue by rockeet** [Tencent/Tendis#101]
### 场景一
在数据批量导入时，希望尽可能得快，这个过程中可以关闭一些不需要的功能，binlog 就是一个典型。

### 场景二
对一些临时数据，我们也不需要高可用，不需要主从，从而也不需要 binlog。

## Expected Behavior
通过配置参数，关闭 binlog

## Current Behavior
binlog 无法关闭

**Comment by raffertyyu** [comment]
已在2.5.0中添加了对binlog功能以及对binlog 导出功能的控制。欢迎反馈。
