### ISSUE TITLE
scan 数据无数据

### ISSUE THREAD

**Issue by jackerzhou** [Tencent/Tendis#106]
## Description

使用scan 0 扫描数据，结果为(empty list or set)
## Expected Behavior

![2](https://user-images.githubusercontent.com/15244380/118241598-ed27c000-b4ce-11eb-902e-0fcabfe4b76c.png)

## Your Environment

* Operating System and version:
* Machine Specifications:   
* Tendis Version: redis_version:2.1.2-rocksdb-v5.13.4
* Tendis Configuration:
* IO/Network used:
* Link to your project:

**Comment by Evil-crow** [comment]
你好,根据上述反应情况. `info server `结果显示版本为 `redis_version:2.1.2-rocksdb-v5.13.4 `
目前 `Scan `命令在 ver 2.2.0后提供支持. 请更新版本至最新后再次尝试.
