### ISSUE TITLE
集群模式scan丢了一部分key，版本2.3.1

### ISSUE THREAD

**Issue by yuandongjian** [Tencent/Tendis#108]
![image](https://user-images.githubusercontent.com/35158271/118633531-2aa88800-b804-11eb-8c8c-95cd450dbdc8.png)

**Comment by yuandongjian** [comment]
这个scan结果具体是什么原因呢？
![image](https://user-images.githubusercontent.com/35158271/118634005-a86c9380-b804-11eb-8d45-a399417673d2.png)

**Comment by TendisDev** [comment]
从上图结果看
k1在节点51003
k2,k3在节点51001。

如果在51001执行scan，只包含k2,k3
如果在51003执行scan，只包含k1

scan是一个节点命令，只能返回当前节点的数据


如果希望实现扫描整个集群的所有数据，需要对每个master节点依次执行scan

**Comment by yuandongjian** [comment]
明白了，tendis的集群模型类似redis cluster，依赖客户端的move指令重定向
而scan不会产生move指令，而且redis-cli也没有对集群模式scan做支持

**Comment by TendisDev** [comment]
是的
