### ISSUE TITLE
Transaction Commands watch discard not support

### ISSUE THREAD

**Issue by chenxyzl** [Tencent/Tendis#112]
## Description
![image](https://user-images.githubusercontent.com/11977514/119448362-d05b7a00-bd63-11eb-9b53-132801ef94d8.png)
![image](https://user-images.githubusercontent.com/11977514/119448496-026cdc00-bd64-11eb-853d-4b31ff08df19.png)

## Expected Behavior
These commands are supported

## Current Behavior
not supported

## Your Environment

* Operating System and version: ubuntu 20.04
* Machine Specifications:   
* Tendis Version: 2.3.1
* Tendis Configuration: default
* IO/Network used: default
* Link to your project: https://github.com/AsynkronIT/protoactor-dotnet

**Comment by raffertyyu** [comment]
We have no plans for this at the moment.
