### ISSUE TITLE
Tendis怎么从低版本升级为高版本

### ISSUE THREAD

**Issue by wenfengwang** [Tencent/Tendis#129]
请问Tendis怎么从低版本升级为高版本，找了下文档没有找到相关资料？

**Comment by flywukong** [comment]
升级有原地升级 和 挂从升级两种。

原地升级：
使用新版本介质替换slave节点介质->重启slave->等待主从同步->slave执行failover命令升主->重启old master

挂从升级：
增加slave节点（使用新版本介质）-> 等待主从同步->slave执行failover命令升主->下架old master 节点

后面文档会完善一下

**Comment by wenfengwang** [comment]
多谢
