### ISSUE TITLE
如何正确理解主从同步的lag和binlog_lag

### ISSUE THREAD

**Issue by wenfengwang** [Tencent/Tendis#131]
根据文档 http://tendis.cn/#/Tendisplus/%E5%91%BD%E4%BB%A4/info?id=replication 中的说明
- lag是从落后主的时间，单位是秒
- binlog_lag表示还有多少个binlog没有发给slave

问题是：
1. lag的落后时间的统计口径或统计算法是什么样子的？
2. 一个binlog是对应一个redis cmd的operation吗？

另外这个图是我们内部集群的一个master的同步信息，这个节点和slave正处于全量同步状态，但是它的lag=0，但是binlog_lag差了很多，这个该如何理解呢？

![image](https://user-images.githubusercontent.com/9766821/125413595-0e09d961-a557-4de4-b118-2e7d988d699b.png)

**Comment by flywukong** [comment]
lag是slave 某个kvstore最近一次执行binlog的时间和当前时间的时间差，单位是秒
一个binlog可以理解成类似mysql数据库提交一个事务生成的记录 , 每个事务 提交后会生成一个binlogID表示db的水位，binlog_lag计算的水位之间的差距

**Comment by vinchen** [comment]
因为当前主从还有部分数据正在全量同步（类似redis的rdb同步），观察`state=send_bulk`，相当于binlog还没开始发送，所以binlog_lag会比较大
当所有`state=online`的时候，lag表示数据落后秒数，binlog_lag表示binlog落后条数，一般情况下关注`lag`即可

**Comment by wenfengwang** [comment]
多谢两位解释
