### ISSUE TITLE
有计划支持pipeline么

### ISSUE THREAD

**Issue by alexKeleon** [Tencent/Tendis#135]
在使用过程中，还是会有事务的需求

**Comment by vinchen** [comment]
未来会支持，但当前还没有具体计划

很欢迎社区能够参与共建

**Comment by mzygQAQ** [comment]
老哥你说的不是pipeline吧? 应该是MULTI EXEC这个

**Comment by silencer001** [comment]
pipeline跟事务是两回事哦，pipeline是客户端的一种发送方式，把多个命令批量写入socket中，但Redis侧没办法保证一次性批量执行完这些命令。
说起来，Redis因为是单线程模型，能保证pipeline的返回结果的顺序一致性，Tendis能保证吗

**Comment by TendisDev** [comment]
> pipeline跟事务是两回事哦，pipeline是客户端的一种发送方式，把多个命令批量写入socket中，但Redis侧没办法保证一次性批量执行完这些命令。 说起来，Redis因为是单线程模型，能保证pipeline的返回结果的顺序一致性，Tendis能保证吗

可以的，这是基本要求
