### ISSUE TITLE
info Replication

### ISSUE THREAD

**Issue by java-fei** [Tencent/Tendis#138]
## Description

版本 2.3.4-rocksdb-v5.13.4，三节点主从，两个主从都正常，一个节点显示有问题。
主库显示没有延迟，从库的lag显示还有延迟。
![image](https://user-images.githubusercontent.com/16696899/127130113-1026ed90-f08b-4923-840b-059e8003bccb.png)

![image](https://user-images.githubusercontent.com/16696899/127130297-a3c19b35-24db-46fc-a57d-12a625f30d44.png)

## Your Environment

* Operating System and version:
* Machine Specifications:   
* Tendis Version:
* Tendis Configuration:
* IO/Network used:
* Link to your project:

**Comment by vinchen** [comment]
这个原因是`lag`是一个负数，但以无符号显示出来
`lag =slave的当前时间戳 - binlog在master生成时间戳`

`lag`是负数的原因是，主备的时钟不一致，备机的时钟比master慢，导致binlog在master生成的时间戳比slave的当前时间还大。

解决办法
1. 调整slave的时钟，跟master保持一致
2. 新版本2.4.0会修复`lag`为负数的显示问题，待发布

**Comment by TendisDev** [comment]
该问题已修复，可以获取最新版本
