### ISSUE TITLE
在Intel Xeon机器上运行报illegal instruction (core dumped)错误

### ISSUE THREAD

**Issue by 0Jvang** [Tencent/Tendis#139]
## Description

- 编译环境
cpu：AMD Ryzen 7 3700X（x86_64）
操作系统：centos7虚拟机
- 运行环境
cpu：Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz（x86_64）
操作系统：centos7

执行`tendisplus tendisplus.conf`报错：illegal instruction (core dumped)

## Expected Behavior

正常启动
## Current Behavior

输出illegal instruction (core dumped)
## Possible Solution

在Intel(R) Xeon(R)机器上编译的版本可以正常运行
## Your Environment

* Operating System and version:
* Machine Specifications:   
* Tendis Version:
* Tendis Configuration:
* IO/Network used:
* Link to your project:

**Comment by jingjunLi** [comment]
* 原因分析
编译机 和 运行机 的 CPU 型号不同, 支持的指令集不同。不兼容的指令集主要有: SSE4.2 和 AVX2。
如果 编译机支持 AVX2, 运行机不支持, 就会出现 `Illegal instruction (core dumped)` 的问题。

* 编译机为什么会使用 运行机不支持的 指令集 ?
主要因为 编译 RocksDB 的时候使用了下面的编译选项: `-march=native`, 允许使用编译机上所有支持的指令集。

* 解决方案
如果想要支持不同编译机和运行机, 可以启用 `PORTABLE` 编译选项。
![编译问题_2021-11-03-10-54-54](https://user-images.githubusercontent.com/11239387/140004124-9d39b62f-c80d-41ab-94d6-20d6189f2d43.png)

**Comment by 0Jvang** [comment]
谢谢

**Comment by klin111** [comment]
thank you
