### ISSUE TITLE
已经两个月没有Commit了，是在憋什么大招嘛~~~

### ISSUE THREAD

**Issue by yuandongjian** [Tencent/Tendis#141]
RT

**Comment by TendisDev** [comment]
你好，2.3.6-rocksdb-v5.13.4 的代码已更新，详细可看版本日志
2.4.0内部正在回归测试。

tendis会持续更新和迭代，感谢对tendis的关注

**Comment by TendisDev** [comment]
2.4.2已发布，详细可以在
