### ISSUE TITLE
2.3.5-rocksdb-v5.13.4 稳定运行一段时间后，报错accept失败，并coredump

### ISSUE THREAD

**Issue by corznoc** [Tencent/Tendis#146]
查看堆栈发现，发现core在network/network.cpp的310行：
LOG(FATAL) << "accept failed:" << ex.what();

查看WARNING日志, 发现有打印’accept failed:set_option: Bad file descriptor'

配置文件如下:
cluster-enabled: yes
daemon on
loglvevel notice
rocks.blockcachemb 102400
executorThreadNum 200
truncateBinlogNum 500000
binlogDelRange 1
maxBinlogKeepNum 20
minBinlogKeepSec 86400
jeprof-auto-dump false
netiothreadnum 200

系统版本:
centos 7 x64

**Comment by corznoc** [comment]
大概每隔4个小时core一次

**Comment by corznoc** [comment]
我看accept 失败前面有打Too many Open files错误。

**Comment by corznoc** [comment]
storage/rocks/rocks_kvstore.cpp:2402行打了rocksdb io异常

**Comment by TendisDev** [comment]
可确认下系统配置`ulimit -n`是否足够大

**Comment by corznoc** [comment]
打开文件数，配置的是65535。
查看tendis进程打开的文件数，确实达到上限了。
主要是rocksdb的文件太多了，导致太多的fd被rocksdb占用
