### ISSUE TITLE
Tendis连接问题

### ISSUE THREAD

**Issue by qdleeinuz** [Tencent/Tendis#148]
您好，
我在使用tendis集群模式时，发现每隔15小时，tendis的监控连接显示会全部下降，然后重连，客户端是php-redis4.0.

![image](https://user-images.githubusercontent.com/88647884/128666838-36cae5df-76b0-4a79-8086-17fd69dd67fb.png)

**Comment by TendisDev** [comment]
你好
tendis一般不会主动中止连接
理论上也没有15小时的周期性行为


确定断开时的是否空闲连接？是否用户主动断开空闲连接？

**Comment by qdleeinuz** [comment]
> 你好
> tendis一般不会主动中止连接
> 理论上也没有15小时的周期性行为
> 
> 确定断开时的是否空闲连接？是否用户主动断开空闲连接？

客户端短链接的情景下触发的；长连接时也会有，是进程释放引起，感谢提供思路，Tendis加油。
