### ISSUE TITLE
tendis 遇到的一些稳定运行问题

### ISSUE THREAD

**Issue by seeIT-51** [Tencent/Tendis#151]
1. tendis长时间运行后，爆出 too many open files,  目前ulimit 已开至 65536 如下，
![image](https://user-images.githubusercontent.com/16160730/129126274-d8bbe391-2eb2-44f5-bce2-a9e0b6eca16c.png)
2. 服务器一次意外重启后，tendis无法启动，请问是什么原因呢，看日志有如下信息：
![image](https://user-images.githubusercontent.com/16160730/129292183-81af09b4-2268-4e89-89a8-cfc6f1f0523d.png)

使用版本如下：
![image](https://user-images.githubusercontent.com/16160730/128958243-491cc883-4b41-4aa3-a86f-d8ca70add6b9.png)

**Comment by TendisDev** [comment]
你好，
问题1：建议将ulimit变大到20w
问题2：这个现象第一次看到，请问可以复现？一直重启都无法启动？看起来是IO出错，是否排除硬件故障

**Comment by seeIT-51** [comment]
@TendisDev 
你好，感谢回复;  
问题2是可以复现的，尤其在写入数据的时候，即使不是重启机器，用kill -9 去杀进程，也会出现无法启动的现象  
报错的日志，每次重启还不太相同，如下是其中的几个
![image](https://user-images.githubusercontent.com/16160730/129822961-128ddba7-5726-42fe-aa7d-1f571eb81200.png)
![image](https://user-images.githubusercontent.com/16160730/129823072-05d6e691-5de4-4da9-9bd3-ce7a957d5957.png)
![image](https://user-images.githubusercontent.com/16160730/129823255-a7432ca1-f600-4625-ada5-9301238e4172.png)

**Comment by TendisDev** [comment]
@seeIT-51  
你的操作系统版本是？
能否尝试下自己编译一个二进制试试

这里出错都是rocksdb调用底层接口出错，尝试下本地编译，排除下二进制不兼容的情况

kill -9 杀进程是常规的测试，目前没遇到这个情况

**Comment by seeIT-51** [comment]
@TendisDev 
系统是：
![image](https://user-images.githubusercontent.com/16160730/129828484-3d0cc6e2-8495-4f34-817b-46fc7a9ac00b.png)
内核版本：
![image](https://user-images.githubusercontent.com/16160730/129828540-be833652-397b-4ec7-8ed5-4b3df968d2c7.png)

每次清除数据后可以启动，我再尝试下本地编译，谢谢。

**Comment by seeIT-51** [comment]
@TendisDev 
问题找到了，是我们的启动脚本写的有些问题，启动脚本挂到了systemctl的服务下，结果tendis重启需要时间长，分配slot的命令执行失败，反馈给systemctl任务服务启动失败，就发了SIGTERM给tendis启动进程，造成了无法启动的假象。
打扰了！
![image](https://user-images.githubusercontent.com/16160730/129854084-e3640936-1722-405f-b40a-f35e20ca6286.png)

另，确认一下，启动一个节点的tendis集群，需要手动分配slot么？
就是启动脚本里面的slot分配命令有必要执行么？

**Comment by TendisDev** [comment]
@seeIT-51 
slot只需分配一次就可以，也不能重复分配

**Comment by seeIT-51** [comment]
@TendisDev 
多谢！
