### ISSUE TITLE
多从节点,主库上执行 info replication 显示的小bug

### ISSUE THREAD

**Issue by earl86** [Tencent/Tendis#157]
redis-cli -h 192.168.1.18 -p 3901      
192.168.1.18:3901> info replication
# Replication
role:master
connected_slaves:2
slave0:ip=192.168.1.20,port=3901,state=online,offset=3181808317,lag=0,binlog_lag=621   这里显示slave0 
slave0:ip=192.168.1.23,port=3901,state=online,offset=3181808249,lag=0,binlog_lag=689   这里正常应该显示slave1
master_repl_offset:3181808938
rocksdb0_slave0:ip=192.168.1.20,port=3901,dest_store_id=0,state=online,binlog_pos=63881599,lag=0,binlog_lag=14
rocksdb0_slave1:ip=192.168.1.23,port=3901,dest_store_id=0,state=online,binlog_pos=63881601,lag=0,binlog_lag=12
rocksdb1_slave0:ip=192.168.1.20,port=3901,dest_store_id=1,state=online,binlog_pos=62563588,lag=0,binlog_lag=11
rocksdb1_slave1:ip=192.168.1.23,port=3901,dest_store_id=1,state=online,binlog_pos=62563585,lag=0,binlog_lag=14

显示的bug
slave0:ip=192.168.1.20,port=3901,state=online,offset=3181808317,lag=0,binlog_lag=621   这里显示slave0 
slave0:ip=192.168.1.23,port=3901,state=online,offset=3181808249,lag=0,binlog_lag=689   这里正常应该显示slave1

* Tendis Version: 2.3.6-rocksdb-v5.13.4

**Comment by TendisDev** [comment]
您好，多谢反馈，修复中

**Comment by raffertyyu** [comment]
已修复。感谢反馈
