### ISSUE TITLE
编译链接失败

### ISSUE THREAD

**Issue by Panshusheng** [Tencent/Tendis#16]
**tendisplus_static link错误报链接库找不到**
[ 95%] Linking CXX executable ../../../bin/tendisplus_static
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[2]: *** [bin/tendisplus_static] Error 1
make[1]: *** [src/tendisplus/server/CMakeFiles/tendisplus_static.dir/all] Error 2
make: *** [all] Error 2

**已经生成的bin是能找到对应的链接库了**
[root@centosVM02 build]# ldd bin/write_stress 
        linux-vdso.so.1 =>  (0x00007ffc57b9a000)
        librocksdb.so.5 => /root/Tendis/build/lib/librocksdb.so.5 (0x00007faa7d7c9000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007faa7d5ad000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00007faa7d3a5000)
        libjemalloc.so.2 => /root/Tendis/src/thirdparty/jemalloc/lib/libjemalloc.so.2 (0x00007faa7cefc000)
        libstdc++.so.6 => /usr/local/gcc-5.5.0/lib64/libstdc++.so.6 (0x00007faa7cb80000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00007faa7c87e000)
        libgcc_s.so.1 => /usr/local/gcc-5.5.0/lib64/libgcc_s.so.1 (0x00007faa7c667000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007faa7c29a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007faa7dff6000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007faa7c096000)

**Comment by TendisDev** [comment]
尝试
make VERBOSE=1
看看最后链接tendisplus_static的输出是什么

**Comment by Panshusheng** [comment]
make VERBOSE=1后的输出

[ 95%] Linking CXX executable ../../../bin/tendisplus_static
cd /root/Tendis/build/src/tendisplus/server && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/tendisplus_static.dir/link.txt --verbose=1
/usr/local/gcc-5.5.0/bin/g++   -std=c++17 -g -fno-omit-frame-pointer  -O2 -Wall -Wextra -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-float-equal -Wendif-labels -Wfloat-equal -Wformat=2 -Wframe-larger-than=69632 -Wmissing-include-dirs -Wpointer-arith -Wwrite-strings -Werror=char-subscripts -Werror=comments -Werror=conversion-null -Werror=empty-body -Werror=endif-labels -Werror=format -Werror=format-nonliteral -Werror=missing-include-dirs -Werror=overflow -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=sign-compare -Werror=switch -Werror=type-limits -Werror=uninitialized -Werror=unused-function -Werror=unused-label -Werror=unused-result -Werror=unused-value -Werror=unused-variable -Werror=write-strings -Wno-invalid-offsetof -Wnon-virtual-dtor -Woverloaded-virtual -Wvla -Werror=non-virtual-dtor -Werror=overloaded-virtual -Werror=vla -O2 -g -DNDEBUG  -rdynamic -static CMakeFiles/tendisplus_static.dir/main.cpp.o  -o ../../../bin/tendisplus_static -Wl,--whole-archive ../../../lib/libcommands.a -Wl,--no-whole-archive ../../../lib/libserver_params.a ../../../lib/libserver.a ../../../../src/thirdparty/jemalloc/lib/libjemalloc.a -ldl -lpthread -lrt ../../../lib/libsync_point.a ../../../lib/libnetwork.a ../../../lib/libnwp.a ../../../lib/librepl_manager.a ../../../lib/libmigrate.a ../../../lib/libcommands.a ../../../lib/libserver_params.a ../../../lib/libserver.a ../../../lib/libnetwork.a ../../../lib/libnwp.a ../../../lib/librepl_manager.a ../../../lib/libmigrate.a ../../../lib/libskiplist.a ../../../lib/libgtest_main.a ../../../lib/libgtest.a ../../../lib/libtime_util.a ../../../lib/librocks_kvstore.a ../../../lib/librocksdb.a ../../../lib/libsnappy.a ../../../lib/liblz4.a ../../../lib/libsegment_mgr.a ../../../lib/libgc_mgr.a ../../../lib/libindex_mgr.a ../../../lib/libcluster_mgr.a ../../../lib/liblock.a ../../../lib/libmgl.a ../../../lib/libpessimistic.a ../../../lib/libsession.a ../../../lib/libsession_ctx.a ../../../lib/libredis_port.a ../../../../src/thirdparty/jemalloc/lib/libjemalloc.a -ldl -lpthread -lrt ../../../lib/libsync_point.a ../../../lib/libcatalog.a ../../../lib/librecord.a ../../../lib/libutils_common.a ../../../lib/libvarint.a ../../../lib/libkvstore.a ../../../lib/libstatus.a ../../../lib/libglog.a -lpthread -lstdc++fs 
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

**Comment by TendisDev** [comment]
执行
` ldconfig -p | grep libpthread`
看看对应库的路径在哪，假设是`$dir`

然后在cmake之前，执行
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`$dir`

**Comment by Panshusheng** [comment]
[root@centosVM02 build]# ldconfig -p | grep libpthread
        libpthread.so.0 (libc6,x86-64, OS ABI: Linux 2.6.32) => /usr/lib64/libpthread.so.0
[root@centosVM02 build]# ldconfig -p| grep  librt     
        librt.so.1 (libc6,x86-64, OS ABI: Linux 2.6.32) => /usr/lib64/librt.so.1
        librt.so (libc6,x86-64, OS ABI: Linux 2.6.32) => /usr/lib64/librt.so
[root@centosVM02 build]# echo $LD_LIBRARY_PATH
/usr/local/gcc-5.5.0/lib64:/usr/local/lib:/usr/lib64:/usr/lib

环境变量是对的

[root@centosVM02 build]# cat /etc/ld.so.conf
include ld.so.conf.d/*.conf
/usr/lib64/
链接一样错误

**Comment by akin520** [comment]
链接不成功，好像bin/tendisplus 编译成功了

**Comment by TendisDev** [comment]
tendisplus_static 是一个完全静态编译的版本，需要`libpthread.a`
如果没有`.a`会提示链接失败

新版修复下cmake脚本，按需生成静态编译版本。

**Comment by TendisDev** [comment]
> 链接不成功，好像bin/tendisplus 编译成功了

一般情况下，运行`bin/tendisplus`即可

**Comment by wangyitian89** [comment]
centos 下, 安装 glibc-static, 可以解决问题.

---
$ rpm -ql glibc-static.x86_64
/usr/lib64/libBrokenLocale.a
/usr/lib64/libanl.a
/usr/lib64/libc.a
/usr/lib64/libc_stubs.a
/usr/lib64/libcrypt.a
/usr/lib64/libdl.a
/usr/lib64/libm.a
/usr/lib64/libnsl.a
/usr/lib64/libpthread.a
/usr/lib64/libresolv.a
/usr/lib64/librt.a
/usr/lib64/libutil.a

**Comment by TendisDev** [comment]
已解决
