### ISSUE TITLE
如何修改配置参数 kvStoreCount?在配置文件里面修改后，程序无法启动，与代码(meta)里面的10相冲突。

### ISSUE THREAD

**Issue by xjj210130** [Tencent/Tendis#168]
## Description
I want to  modify the kvStoreCount in tendisplus.conf. But it can't work. I use the master code

## Expected Behavior
[catalog.cpp:163] kvStoreCount(40,10) or chunkSize(16384,16384) not equal

## Your Environment

* Operating System and version:
* Machine Specifications:   
* Tendis Version:
* Tendis Configuration:
* IO/Network used:
* Link to your project:

**Comment by xjj210130** [comment]
i modify the uint32_t kvStoreCount = 40; in server_params.h

**Comment by jingjunLi** [comment]
kvStoreCount 的修改有以下原则:
  1) 拉起 已有数据的 DB, kvStoreCount 不能修改
  2) 拉起 一个 空的 DB, 可以随意配置。

根据你的描述,  `[catalog.cpp:163] kvStoreCount(40,10) or chunkSize(16384,16384) not equal` 应该是修改一个 已存在数据的 DB， 所以这里是报错的。

**Comment by xjj210130** [comment]
非常感谢
