### ISSUE TITLE
怎么把pika迁移到tendis

### ISSUE THREAD

**Issue by valiner** [Tencent/Tendis#17]
怎么把pika迁移到tendis

**Comment by TendisDev** [comment]
可以尝试先将pika迁移到redis
再从redis迁移到tendis，可参考https://github.com/Tencent/Tendis/issues/7

**Comment by valiner** [comment]
> 可以尝试先将pika迁移到redis
> 再从redis迁移到tendis，可参考#7

几百个g的pika数据，迁redis，迁移不动

**Comment by TendisDev** [comment]
https://github.com/Qihoo360/pika/wiki/pika%e5%88%b0pika%e3%80%81redis%e8%bf%81%e7%a7%bb%e5%b7%a5%e5%85%b7

从官方文档中，pika提供工具迁移到redis，理论上也可以迁移到tendis
