### ISSUE TITLE
请问一下后续的版本开发还有计划吗

### ISSUE THREAD

**Issue by ZoidbergPi** [Tencent/Tendis#175]
主要是单机模式使用，希望能够关闭binlog的dump 每次都要通过脚本辅助删除

**Comment by raffertyyu** [comment]
在近期将发布的2.5.0中就包含了对binlog功能的一些新增配置参数，可以关闭binlog功能以及禁用导出binlog。应该能够解决你的问题。

**Comment by raffertyyu** [comment]
tendisplus 2.5.0中新增了包含了对binlog文件和dump导出功能的控制。
