### ISSUE TITLE
tendisplus 的bind 与 redis的bind 

### ISSUE THREAD

**Issue by zhaochunxue** [Tencent/Tendis#18]
redis的bind指定ip含义是只有当前ip及其网卡上的ip才能连上当前节点
tendisplus在创建集群的时候bind是用来创建集群指定ip使用的。
这个是否有必要更改成和redis的bind相一致

**Comment by TendisDev** [comment]
Thanks for issue.
It should be fixed in next release.

**Comment by TendisDev** [comment]
已解决，请下载最新版本
