### ISSUE TITLE
Will tendis continue develop in the future?

### ISSUE THREAD

**Issue by takkaman** [Tencent/Tendis#181]
I observed that there's no new release published for ~6 month.
Still 7 bugs remaining there and worring about it's quality in the future.

**Comment by raffertyyu** [comment]
Yes, we will release new version soon with many new features and bugs fixed.
The project won't be abandoned since it has be widely used by Tencent.
It's very welcome to open issue when you find bugs. 
Thanks to help us get better.
We are glad to hear from open source community.

**Comment by takkaman** [comment]
Glad to hear that, cheers~

**Comment by takkaman** [comment]
> Yes, we will release new version soon with many new features and bugs fixed. The project won't be abandoned since it has be widely used by Tencent. It's very welcome to open issue when you find bugs. Thanks to help us get better. We are glad to hear from open source community.

Hi, any update so far? As we're evaluating proper storage candidate for our feature development. :-)

**Comment by raffertyyu** [comment]
Yes, we are fixing some performance issues. Maybe in a few weeks.

**Comment by raffertyyu** [comment]
https://github.com/Tencent/Tendis/releases/tag/2.5.0-rocksdb-v6.23.3
Any issues are welcome.

**Comment by takkaman** [comment]
> https://github.com/Tencent/Tendis/releases/tag/2.5.0-rocksdb-v6.23.3 Any issues are welcome.

Appreciate. Really glad to hear the good news.
