### ISSUE TITLE
中国，文档已无法打开

### ISSUE THREAD

**Issue by fly321** [Tencent/Tendis#184]
cdn.jsdelivr.net 已被dns污染

**Comment by raffertyyu** [comment]
请问是tendis.cn吗

我试了一下，广东深圳电信手机可以正常打开，似乎没有这个问题。

方便提供一下网络信息吗，便于定位问题。

**Comment by zeriean** [comment]
![image](https://user-images.githubusercontent.com/84653864/171076313-9abd0f8c-a2e7-468e-96ad-324e28ce1f7c.png)

**Comment by Evil-crow** [comment]
已修复,恢复正常使用

**Comment by fly321** [comment]
已恢复正常使用！
