### ISSUE TITLE
如何配置才能自动清理binlog

### ISSUE THREAD

**Issue by cocoj521** [Tencent/Tendis#186]
目前binlog配置如下：
![tendis-conf](https://user-images.githubusercontent.com/46246299/170829998-e3751ecd-fd5b-4f44-a37f-2e24e8845b07.png)
config get *binlog*  结果如下：
![tendis-conf2](https://user-images.githubusercontent.com/46246299/170830026-11075368-1f7f-48a3-9269-cd91f501b286.png)

但是binlog却只增不减，一个文件都没有自动删除。
如何配置才能自动清理binlog？

**Comment by raffertyyu** [comment]
是这样的。tendis是把用户数据和对用户数据的操作（记录成binlog）分开存放在rocksdb的两个CF中，然后，binlog cf中的数据量会不断的增加（因为binlog只增不减）所以为了保证db目录（也就是rocksdb的数据目录）的磁盘占用不会过于膨胀，tendis会后台周期性的导出binlog到dump目录下面的特殊格式的文件，这个用于之后进行冷备。如果用不上的话可以直接删除。

现有的配置比如maxbinlogkeepnum和minbinlogkeepsec都是为了配置存储于rocksdb binlog cf中的那些binlog的数量。和dump目录下面的binlog文件没关系。在现有版本，暂时没有和这方面有关的配置参数，是需要用户手动进行删除的（比如后台脚本，或者cron任务）。

**Comment by cocoj521** [comment]
OK，明白了。已自制脚本定时删除。
