### ISSUE TITLE
关于将相同的key-value多次写入tendis的问题

### ISSUE THREAD

**Issue by masayil** [Tencent/Tendis#189]
#169 中提到将相同的key-value多次写入tendis磁盘的占用会增加。目前我是只能通过[reshape](https://tendis.cn/#/Tendisplus/%E5%91%BD%E4%BB%A4/reshape?id=reshape)命令进行清理吗？在执行命令的过程中当前节点可以进行读写操作吗？在集群模式中整个操作流程是怎样的？

**Comment by raffertyyu** [comment]
可以，reshape不阻塞读写，底层就是对所有key进行compact
