### ISSUE TITLE
DockerHub中版本未更新

### ISSUE THREAD

**Issue by ZoidbergPi** [Tencent/Tendis#192]
## Description

DockerHub中版本未更新
## Expected Behavior

DockerHub中版本还是2.4.3版本

## Your Environment

* Operating System and version:
* Machine Specifications:   
* Tendis Version:
* Tendis Configuration:
* IO/Network used:
* Link to your project:

**Comment by raffertyyu** [comment]
非常感谢反馈，已经推送了2.5.0版本的镜像~
