### ISSUE TITLE
生成的tendisplus执行文件不可以启动服务

### ISSUE THREAD

**Issue by HBSDLJZ** [Tencent/Tendis#197]
编译生成的tendisplus执行文件，在执行的时候只是输出了如下日志就结束了，后台并没有启动服务，如何解决？请大佬明示~

[root@localhost tmp.Y1QIlpiVuL]# **./tendisplus tendisplus.conf**
start server with cfg:
allow-cross-slot:no
aof-enabled:no
aof-psync-num:500
bind:"127.0.0.1"
binlog-enabled:yes
binlog-save-logs:yes
binlog-send-batch:256
binlog-send-bytes:16777216
binlog-using-defaultCF:no
binlogDelRange:100000
binlogFileSecs:1200
binlogFileSizeMB:64
binlogRateLimitMB:64
checkkeytypeforsetcmd:no
chunkSize:16384
cluster-allow-replica-migration:no
cluster-enabled:no
cluster-migration-barrier:1
cluster-migration-batch-size:16
cluster-migration-binlog-iters:10
cluster-migration-distance:10000
cluster-migration-rate-limit:32
cluster-migration-slots-num-per-task:10
cluster-migration-timeout:5
cluster-node-timeout:15000
cluster-require-full-coverage:yes
cluster-single-node:no
cluster-slave-no-failover:no
cluster-slave-validity-factor:10
compactrange-after-deleterange:no
daemon:yes
databases:16
delCntIndexMgr:10000
deletefilesinrange-for-binlog:yes
deletefilesinrange-for-migrate-gc:no
delJobCntIndexMgr:1
dir:"./home/db"
direct-io:no
domain-enabled:no
dumpdir:"./home/dump"
executorThreadNum:48
executorWorkPoolSize:0
force-recovery:0
fullPsync-notice-enabled:no
fullPushThreadnum:5
fullReceiveThreadnum:5
garbage-delete-size:30
garbageDeleteThreadnum:1
generalLog:no
generate-heartbeat-binlog-interval:0
incrPushThreadnum:10
jeprof-auto-dump:yes
keysDefaultLimit:100
kvStoreCount:10
lockDbXWaitTimeout:1
lockWaitTimeOut:3600
log-error:no
logDir:"./home/log"
logLevel:"notice"
logRecycleThreadnum:5
lua-time-limit:5000
luaStateMaxIdleTime:3600000
masterauth:******
maxBinlogKeepNum:1
maxClients:10000
migrate-gc-enabled:no
migrate-snapshot-key-num:100000
migrate-snapshot-retry-num:1000
migrateReceiveThreadnum:5
migrateSenderThreadnum:5
minBinlogKeepSec:3600
net-send-batch-size:1400
netBatchSize:1048576
netBatchTimeoutSec:10
netIoThreadNum:0
noexpire:no
pauseTimeIndexMgr:1
pidFile:"./home/tendisplus.pid"
port:51002
proto-max-bulk-len:536870912
replicate-fix-enabled:yes
requirepass:******
rocks-transaction-mode:2
rocks.blockcache_num_shard_bits:6
rocks.blockcache_strict_capacity_limit:no
rocks.blockcachemb:4096
rocks.compaction_deletes_ratio:0.000000
rocks.compaction_deletes_trigger:0
rocks.compaction_deletes_window:0
rocks.compress_type:"snappy"
rocks.delete_bytes_per_second:0
rocks.disable_wal:no
rocks.flush_log_at_trx_commit:no
rocks.level0_compress_enabled:no
rocks.level1_compress_enabled:no
rocks.max_background_jobs:2
rocks.max_open_files:-1
rocks.rate_limiter_auto_tuned:yes
rocks.rate_limiter_fairness:10
rocks.rate_limiter_rate_bytes_per_sec:0
rocks.rate_limiter_refill_period_us:100000
rocks.skip_concurrency_control:no
rocks.wal_dir:""
save-min-binlogid:yes
scanCntIndexMgr:1000
scanDefaultLimit:10
scanDefaultMaxIterateTimes:10000
scanJobCntIndexMgr:1
slave-migrate-enabled:no
slaveBinlogKeepNum:1
slowlog:"./home/log/slowlog"
slowlog-file-enabled:yes
slowlog-flush-interval:1000
slowlog-log-slower-than:100000
slowlog-max-len:128
storage:"rocks"
supply-fullpsync-key-batch-num:100
tbitmap-fragment-size:1024
timeoutSecBinlogWaitRsp:3
truncateBinlogIntervalMs:1000
truncateBinlogNum:100000
version-increase:yes
wait-time-if-exists-migrate-task:600

**Comment by takenliu** [comment]
默认是后台daemon方式启动的，如果不想daemon方式的话可以添加配置：daemon 0

**Comment by hardeagle** [comment]
tendisplus.conf的默认配置需要创建以下目录
./home/db/catalog/

**Comment by raffertyyu** [comment]
tendisplus默认以后台daemon的方式运行。可以通过添加配置
```
daemon 0
```
禁用该行为。

另外tendisplus需要在运行前确保配置文件中的`dir` `logdir` 目录的存在。可以通过`mkdir`手动创建
