### ISSUE TITLE
如何修改rocksdb的配置文件？

### ISSUE THREAD

**Issue by HBSDLJZ** [Tencent/Tendis#198]
tendisplus.conf中rocksdb可配置参数少于rocksdb原有的，如何配置rocksdb原有的参数？

**Comment by takenliu** [comment]
目前tendis暴露了大部分rocksdb的参数配置，但并没有支持全部的参数，后续考虑优化。
如果你想紧急使用某个没有支持的参数，可以在rocks_kvstore.cpp文件的rocksdbOptionsSet和rocksdbTableOptionsSet两个函数里面添加相关配置代码。
