### ISSUE TITLE
Update RocksDB to latest (6.14.6)

### ISSUE THREAD

**Issue by acacio** [Tencent/Tendis#22]
As $SUBJECT says, the current shipped version of RocksDB is quite old.

Do you rely on any incompatible APIs on that version or can we just replace with latest release?

[v6.14.6](https://github.com/facebook/rocksdb/releases/tag/v6.14.6) is the latest tag.

**Comment by jingjunLi** [comment]
Good suggestions!
We are going to upgrade the version of RocksDB to 6.X in the next release. Now we have referenced some incompatible APIs of RocksDB (5.13.4 vs 6.14), we will changes these API during the upgrade process. Thanks for your suggestion ~

**Comment by raffertyyu** [comment]
Tendis 2.5.0 is now using rocksdb 6.23.3 and will update rocksdb more frequent in the future.
