### ISSUE TITLE
question:  tendis删除大key，磁盘空间未释放，是否正常？

### ISSUE THREAD

**Issue by erwadba** [Tencent/Tendis#226]
复现步骤：
1. 3主3从
2.  rpush  key1  [ value1, value2 ...]    写入 13亿条数据， 落在 主1  机器，硬盘占用22G
3.  rpush  key2  [ value1, value2 ...]    写入 13亿条数据， 落在 主2  机器， 硬盘占用22G
4.  del  key1 ;   compactrange data  0  5461         //主1 机器，删除key1，compact 对应的slots
5.  主1 机器的硬盘还是占用 22G，没有任何减少，过了一天还是没任何减少。这个是否是正常的现象。删除数据之后，磁盘应该正常释放吧？

**Comment by zyqlzr** [comment]
在del key之后，使用compackrange命令而不是compackslots命令，compactslots命令目前存在一个bug，在2.5.0之后会修复。
