### ISSUE TITLE
对比 Tcaplus 有什么特别的优势吗？

### ISSUE THREAD

**Issue by Yu2erer** [Tencent/Tendis#23]
如题

**Comment by TendisDev** [comment]
tcaplus是腾讯内部非常优秀的KV存储，主要用于游戏场景，使用自研协议，自研游戏使用较多

tendis是基于redis生态做的分布式存储，主要面向redis的使用者，使用redis协议，便于redis用户的平滑过渡，对代理游戏和共有云上用户更为友好。
