### ISSUE TITLE
请问dump文件夹是放什么数据的，可以删除吗？

### ISSUE THREAD

**Issue by valiner** [Tencent/Tendis#24]
请问dump文件夹是放什么数据的，可以删除吗？

**Comment by valiner** [comment]
有什么版本取消binlog的生成吗，因为我们的业务是3主，不需要binlog

**Comment by valiner** [comment]
有什么办法取消binlog的生成吗，因为我们的业务是3主，不需要binlog

**Comment by TendisDev** [comment]
dump文件中的内容，可以认为类似于mysql的binlog

除了最后一个binlog文件（有可能正在写），其他文件是可以删除的

这些文件的作用主要用于回档。


目前没有办法取消binlog的生成

**Comment by TendisDev** [comment]
Duplicate of #36

**Comment by raffertyyu** [comment]
在2.5.0版本中已经新增参数控制binlog功能以及导出binlog功能的开启与否。欢迎体验。

**Comment by raffertyyu** [comment]
tendis 2.5.0 已经添加了对binlog功能，以及binlog导出功能的控制。欢迎使用。
