### ISSUE TITLE
2.6.0版本 memtier_benchmark 压测 纯set，内存无限制增长

### ISSUE THREAD

**Issue by wanjianjun123** [Tencent/Tendis#246]
2.6.0版本，用memtier_benchmark压测set，tendis进程的占用内存在无限制的上涨

压测命令：
`memtier_benchmark -t 20 -c 50 -s xx.xx.xx.xx -p 3901 -a 123456 --distinct-client-seed --command="set __key__ __data__" --key-prefix="kv_" --key-minimum=1 --key-maximum=50000000 --random-data --data-size=128 --test-time=1800`

配置文件：```
bind xx.xx.xx.xx
port 3901

pidfile /data/tendis/test-tendis1/tmp/tendisplus.pid
logdir /data/tendis/test-tendis1/log
dir /data/tendis/test-tendis1/db
dumpdir /data/tendis/test-tendis1/dump
slowlog /data/tendis/test-tendis1/slowlog/slowlog

requirepass 123456
masterauth 123456

daemon no
loglevel notice
cluster-enabled 0
storage rocks
maxclients 200000
jeprof-auto-dump 0
checkkeytypeforsetcmd no

slowlog-file-enabled 1
slowlog-log-slower-than 100000

minBinlogKeepSec 3600
truncateBinlogIntervalMs 1000
truncateBinlogNum 5000000
binlogDelRange 500000

noexpire false

netiothreadnum 32
executorWorkPoolSize 8
executorthreadnum 64
incrPushThreadnum 25
fullPushThreadnum 8
fullReceiveThreadnum 4
logRecycleThreadnum 4

binlogRateLimitMB 64

kvstorecount 50
rocks.blockcachemb 98304
rocks.blockcache_strict_capacity_limit 0
rocks.cache_index_and_filter_blocks 1
rocks.max_open_files -1

rocks.flush_log_at_trx_commit 0
rocks.compress_type lz4
rocks.level_compaction_dynamic_level_bytes 1
rocks.target_file_size_base 67108864
rocks.max_bytes_for_level_base 536870912
rocks.write_buffer_size 67108864
rocks.max_write_buffer_number 256
rocks.min_write_buffer_number_to_merge 2
rocks.max_background_jobs 64
rocks.max_background_compactions 60
rocks.max_background_flushes 4
rocks.max_subcompactions 4
rocks.level0_file_num_compaction_trigger 8
rocks.level0_slowdown_writes_trigger 192
rocks.level0_stop_writes_trigger 256

cluster-migration-slots-num-per-task 100
cluster-migration-rate-limit 1000
cluster-migration-binlog-iters 20
cluster-migration-distance 10000
cluster-migration-timeout 10

cluster-node-timeout 15000
cluster-slave-validity-factor 10
cluster-require-full-coverage yes

cluster-slave-no-failover no

mapping-command dbsize emptyint
mapping-command keys emptymultibulk
rename-command flushdb flushdb_rename
rename-command flushall flushall_rename
rename-command flushalldisk flushalldisk_rename
```

**Comment by takenliu** [comment]
内存问题参考：
http://tendis.cn/#/Tendisplus/知识库/FAQ
Q: tendis的内存占用是多少
