### ISSUE TITLE
[question] update detail doc

### ISSUE THREAD

**Issue by rfyiamcool** [Tencent/Tendis#25]
[http://tendis.cn/#/Tendisplus/%E8%BF%90%E7%BB%B4/migrate](http://tendis.cn/#/Tendisplus/%E8%BF%90%E7%BB%B4/migrate)

😅 很是好奇，在tendis里如何实现的一致性安全迁移，毕竟迁移过程中 `src node` 也有写操作，好奇是如何处理的？  

我看文档中只是说明了是异步模式迁移数据，那么应该必然不会跟redis cluster那样阻塞的迁移。

![http://tendis.cn/Tendisplus/%E8%BF%90%E7%BB%B4/pic/migrate_command1.png](http://tendis.cn/Tendisplus/%E8%BF%90%E7%BB%B4/pic/migrate_command1.png)

**Comment by flywukong** [comment]
内部实现了slot 锁，可以实现slot 搬迁的并发控制，在搬迁最后快结束的时候，会对src node 搬迁的slot上锁阻塞读请求，当dst node修改完元数据后通知 src node会解锁修改元数据， 细节参考下面的链接：
http://tendis.cn/#/Tendisplus/%E7%9F%A5%E8%AF%86%E5%BA%93/%E9%9B%86%E7%BE%A4/tendis_migrate

**Comment by rfyiamcool** [comment]
👍 谢谢，设计很是巧妙 !

先全量，再增量，两节点数据差快接近时，加锁，同步最后差值数据，修改状态，放锁。

**Comment by rfyiamcool** [comment]
不好意思，再请教个问题。。。 😅

配置文件中 `kvstorecount ` 指明多个rocksdb的实例数量？ 那么读写的时候怎么查找对应的rocksdb实例。 另外，文档中说，为了实现写请求和binlog的一致性，他们包在一个事务里写在一个rocksdb里吧？ 那么主从同步的时候，如何在众多rocksdb存储里找到对应的binlog offset ？

忘解答...

**Comment by TendisDev** [comment]
key跟rocksdb的关系：
当满足如下条件时，key会存储到相应的rocksdb(kvstore)中
slot_of_key % kvstorecount == kvstore_id

每个kvstore独立管理自己的binlog和key，在tendis内部，主备之间的每个rocksdb拥有独立的同步链路
