### ISSUE TITLE
failover time out

### ISSUE THREAD

**Issue by githubname1024** [Tencent/Tendis#251]
## Description
三主三从的tendis集群，对任一slave执行cluster failover或cluster failover force均报超时。cluster failover takeover能成功。

## Expected Behavior
期望能正确的执行cluster failover和cluster failover force.

## Current Behavior
**cluster failover 从节点日志**
W1020 14:07:10.664491 4293 cluster_manager.cpp:1761] Manual failover user request accepted.
W1020 14:07:10.747529 4366 cluster_manager.cpp:5384] Received replication offset for paused master manual failover: 67030 67030
E1020 14:07:10.753872 4367 cluster_manager.cpp:2486] All master replication stream processed, manual failover can start.
E1020 14:07:10.854060 4367 cluster_manager.cpp:2466] mf_can_start is non-zero
E1020 14:07:10.954180 4367 cluster_manager.cpp:2466] mf_can_start is non-zero
....(中间省略很多条mf_can_start is non-zero日志)
E1020 14:07:15.559863 4367 cluster_manager.cpp:2466] mf_can_start is non-zero
E1020 14:07:15.659952 4367 cluster_manager.cpp:2466] mf_can_start is non-zero
E1020 14:07:15.760082 4367 cluster_manager.cpp:2410] Manual failover timed out.

**cluster failover force从节点日志**
E1020 14:09:36.411868 4297 cluster_manager.cpp:1758] Forced failover user request accepted.
E1020 14:09:36.478754 4367 cluster_manager.cpp:2466] mf_can_start is non-zero
E1020 14:09:36.578848 4367 cluster_manager.cpp:2466] mf_can_start is non-zero
E1020 14:09:36.678997 4367 cluster_manager.cpp:2466] mf_can_start is non-zero
....(中间省略很多条mf_can_start is non-zero日志)
E1020 14:09:41.183677 4367 cluster_manager.cpp:2466] mf_can_start is non-zero
E1020 14:09:41.283859 4367 cluster_manager.cpp:2466] mf_can_start is non-zero
E1020 14:09:41.383957 4367 cluster_manager.cpp:2466] mf_can_start is non-zero
E1020 14:09:41.484058 4367 cluster_manager.cpp:2410] Manual failover timed out.

## Possible Solution
未找到解决办法

## Your Environment
* Operating System and version: Centos 7
* Tendis Version: 2.6.0
* Tendis Configuration: 

1) "allow-cross-slot"
2) "no"
3) "aof-enabled"
4) "no"
5) "aof-psync-num"
6) "500"
7) "bind"
8) "\"0.0.0.0\""
9) "bind2"
10) "\"\""
11) "binlog-enabled"
12) "yes"
13) "binlog-save-logs"
14) "yes"
15) "binlog-send-batch"
16) "256"
17) "binlog-send-bytes"
18) "16777216"
19) "binlog-using-defaultcf"
20) "no"
21) "binlogdelrange"
22) " not supported anymore"
23) "binlogfilesecs"
24) "1200"
25) "binlogfilesizemb"
26) "64"
27) "binlogratelimitmb"
28) "64"
29) "checkkeytypeforsetcmd"
30) "no"
31) "chunksize"
32) "16384"
33) "cluster-allow-replica-migration"
34) "no"
35) "cluster-enabled"
36) "yes"
37) "cluster-migration-barrier"
38) "1"
39) "cluster-migration-batch-size"
40) "16"
41) "cluster-migration-binlog-iters"
42) "10"
43) "cluster-migration-distance"
44) "10000"
45) "cluster-migration-rate-limit"
46) "32"
47) "cluster-migration-slots-num-per-task"
48) "10"
49) "cluster-migration-timeout"
50) "5"
51) "cluster-node-timeout"
52) "15000"
53) "cluster-require-full-coverage"
54) "yes"
55) "cluster-single-node"
56) "no"
57) "cluster-slave-no-failover"
58) "yes"
59) "cluster-slave-validity-factor"
60) "10"
61) "compactrange-after-deleterange"
62) "no"
63) "daemon"
64) "yes"
65) "databases"
66) "16"
67) "delcntindexmgr"
68) "10000"
69) "deletefilesinrange-for-binlog"
70) " not supported anymore"
71) "deletefilesinrange-for-migrate-gc"
72) "yes"
73) "deljobcntindexmgr"
74) "1"
75) "dir"
76) "\"/data/tendis-31030/\""
77) "direct-io"
78) "no"
79) "domain-enabled"
80) "no"
81) "dumpdir"
82) "\"/data/tendis-31030/dump/\""
83) "element-limit-for-single-delete"
84) "2048"
85) "element-limit-for-single-delete-zset"
86) "1024"
87) "executorthreadnum"
88) "56"
89) "executorworkpoolsize"
90) "8"
91) "force-recovery"
92) "0"
93) "fullpsync-notice-enabled"
94) "no"
95) "fullpushthreadnum"
96) "5"
97) "fullreceivethreadnum"
98) "5"
99) "garbage-delete-size"
100) " not supported anymore"
101) "garbagedeletethreadnum"
102) " not supported anymore"
103) "generallog"
104) "no"
105) "generate-heartbeat-binlog-interval"
106) "0"
107) "incrpushthreadnum"
108) "10"
109) "jeprof-auto-dump"
110) "yes"
111) "keysdefaultlimit"
112) "100"
113) "kvstorecount"
114) "10"
115) "lockdbxwaittimeout"
116) "1000"
117) "lockwaittimeout"
118) "3600"
119) "log-error"
120) "no"
121) "logdir"
122) "\"/data/tendis-31030/log/\""
123) "loglevel"
124) "\"\""
125) "logrecyclethreadnum"
126) "5"
127) "lua-time-limit"
128) "5000"
129) "luastatemaxidletime"
130) "3600000"
131) "masterauth"
132) "\"xxxxxxxxxxxxxxxxxxxxx\""
133) "maxbinlogkeepnum"
134) "1"
135) "maxclients"
136) "10000"
137) "migrate-gc-enabled"
138) " not supported anymore"
139) "migrate-snapshot-key-num"
140) "100000"
141) "migrate-snapshot-retry-num"
142) "1000"
143) "migratereceivethreadnum"
144) "5"
145) "migratesenderthreadnum"
146) "5"
147) "minbinlogkeepsec"
148) "3600"
149) "net-send-batch-size"
150) " not supported anymore"
151) "netbatchsize"
152) "1048576"
153) "netbatchtimeoutsec"
154) "10"
155) "netiothreadnum"
156) "12"
157) "noexpire"
158) "no"
159) "pausetimeindexmgr"
160) "1"
161) "pidfile"
162) "\"/data/tendis-31030/tendisplus.pid\""
163) "port"
164) "31030"
165) "proto-max-bulk-len"
166) "536870912"
167) "replicate-fix-enabled"
168) "yes"
169) "requirepass"
170) "\"xxxxxxxxxxxxxxxxxxx\""
171) "rocks-transaction-mode"
172) "2"
173) "rocks.blockcache_num_shard_bits"
174) "6"
175) "rocks.blockcache_strict_capacity_limit"
176) "no"
177) "rocks.blockcachemb"
178) "4096"
179) "rocks.compaction_deletes_ratio"
180) "0.000000"
181) "rocks.compaction_deletes_trigger"
182) "0"
183) "rocks.compaction_deletes_window"
184) "0"
185) "rocks.compress_type"
186) "\"snappy\""
187) "rocks.delete_bytes_per_second"
188) "0"
189) "rocks.disable_wal"
190) "no"
191) "rocks.flush_log_at_trx_commit"
192) "no"
193) "rocks.latency-limit"
194) "0"
195) "rocks.level0_compress_enabled"
196) "no"
197) "rocks.level1_compress_enabled"
198) "no"
199) "rocks.max_background_jobs"
200) "2"
201) "rocks.max_open_files"
202) "100"
203) "rocks.rate_limiter_auto_tuned"
204) "yes"
205) "rocks.rate_limiter_fairness"
206) "10"
207) "rocks.rate_limiter_rate_bytes_per_sec"
208) "0"
209) "rocks.rate_limiter_refill_period_us"
210) "100000"
211) "rocks.rowcachemb"
212) "0"
213) "rocks.skip_concurrency_control"
214) "no"
215) "rocks.wal_dir"
216) "\"\""
217) "save-min-binlogid"
218) " not supported anymore"
219) "scancntindexmgr"
220) "1000"
221) "scandefaultlimit"
222) "10"
223) "scandefaultmaxiteratetimes"
224) "10000"
225) "scanjobcntindexmgr"
226) "1"
227) "slave-migrate-enabled"
228) "no"
229) "slavebinlogkeepnum"
230) "1"
231) "slowlog"
232) "\"/data/tendis-31030/log/slowlog/\""
233) "slowlog-file-enabled"
234) "yes"
235) "slowlog-flush-interval"
236) "1000"
237) "slowlog-log-slower-than"
238) "100000"
239) "slowlog-max-len"
240) "128"
241) "storage"
242) "\"rocks\""
243) "supply-fullpsync-key-batch-num"
244) "100"
245) "tbitmap-fragment-size"
246) "1024"
247) "tendis-latency-limit"
248) "0"
249) "timeoutsecbinlogwaitrsp"
250) "3"
251) "truncatebinlogintervalms"
252) "1000"
253) "truncatebinlognum"
254) "10000"
255) "version-increase"
256) "yes"
257) "wait-time-if-exists-migrate-task"
258) "600"
259) "rocks.cache_index_and_filter_blocks"
260) "1"

**Comment by zyqlzr** [comment]
参数配置cluster-slave-no-failover不能设置为true
