### ISSUE TITLE
无法搬迁仅有的一个slot

### ISSUE THREAD

**Issue by wavelet123** [Tencent/Tendis#264]
## Description

试图搬迁13383 这一个槽位是报错
cc6f2cea84381e0f45e042f040ad040ee7ca1c23 172.28.x.x:3690@13690 master - 0 1711087493497 4 connected 13383
31dbcdd19bc1bbcaef12ba7d1841c685a75d3cfa 172.28.x.x:3689@13689 master - 0 1711087494497 2 connected 5462-10922
17b66940a0e796940667e433ac87eccb00e9188f 172.28.x.x:3689@13689 master - 0 1711087493000 1 connected 0-5461
610515566ca4dbf0dfa52777aaf531f0e0dd9472 172.28.x.x:3689@13689 myself,master - 0 1711087493000 5 connected 10923-13382 13384-16383

(error) ERR:18,msg:start position should be less than end
172.28.33.94:3689> cluster setslot importing cc6f2cea84381e0f45e042f040ad040ee7ca1c23 {13383..13384}
(error) ERR:18,msg:I'm already the owner of hash slot13384
172.28.33.94:3689> cluster setslot importing cc6f2cea84381e0f45e042f040ad040ee7ca1c23 {13382..13383}
(error) ERR:18,msg:I'm already the owner of hash slot13382

## Your Environment

* Operating System and version:
* Machine Specifications:   
* Tendis Version:tendisplus-2.7.0-rocksdb-v8.5.3
* Tendis Configuration:
* IO/Network used:
* Link to your project:

**Comment by raffertyyu** [comment]
端口号直接输入13383，{}花括号表达式是闭区间。

**Comment by wavelet123** [comment]
> 端口号直接输入13383，{}花括号表达式是闭区间。

确实可以解决
