### ISSUE TITLE
tendis setslot报错

### ISSUE THREAD

**Issue by wavelet123** [Tencent/Tendis#265]
## Description

cluster setslot importing 9755b415753ae7fc7537867c5a36779a8e105e7b {5462..10922} 报错
(error) ERR:1,msg:json parse fail
命令没错，但是一直报错
## Your Environment

* Operating System and version:
* Machine Specifications:   
* Tendis Version: tendisplus-2.7.0-rocksdb-v8.5.3
* Tendis Configuration:
* IO/Network used:
* Link to your project:

**Comment by raffertyyu** [comment]
能麻烦简单发下复现步骤吗

**Comment by wavelet123** [comment]
> 能麻烦简单发下复现步骤吗

![image](https://github.com/Tencent/Tendis/assets/11556213/47e809ed-3649-46c6-9446-cbbaae999979)
搭建的3节点空集群，操作一样报错，上周都正常

**Comment by wavelet123** [comment]
> 能麻烦简单发下复现步骤吗

7ce69307228f00e61cbe9dd6e3ca7c4c02c1d4a9 172.x.33.94:3689@13689 master - 0 1711507508000 0 connected 10923-16383
684ec60c6dded4870c1cf9fdf84b4d50b66c54a5 172.x.32.162:3689@13689 master - 0 1711507509546 2 connected 5462-10922
0020fe84a3a23937c0ed565c3c007e268cfac048 172.x.34.46:3689@13689 myself,master - 0 1711507509000 1 connected 0-5461
172.x.34.46:3689> cluster setslot importing 684ec60c6dded4870c1cf9fdf84b4d50b66c54a5 7365
(error) ERR:1,msg:json parse fail
172.x.34.46:3689> cluster setslot importing 684ec60c6dded4870c1cf9fdf84b4d50b66c54a5 {7365..7366}
(error) ERR:1,msg:json parse fail
172.x.34.46:3689> cluster setslot importing 684ec60c6dded4870c1cf9fdf84b4d50b66c54a5 10922
(error) ERR:1,msg:json parse fail
172.x.34.46:3689> cluster setslot importing 684ec60c6dded4870c1cf9fdf84b4d50b66c54a5 {10921..10922}
(error) ERR:1,msg:json parse fail

**Comment by wavelet123** [comment]
4beb6579838c5a7288f41fffd4c23d8d218a0684 172.x.33.94:3689@13689 master - 0 1711522694000 0 connected 5462-10922
15be89748bc2aa8f177a32b10656051ce94a60b8 172.x.32.162:3689@13689 master - 0 1711522694862 2 connected 10923-16383
04011b23919b2d31ee6bf755048ac78870bd0bd3 172.x.34.46:3689@13689 master - 0 1711522694000 1 connected 0-5461
3447c546472ecafc03f0560ce60aa10915926f72 172.x.32.162:3690@13690 myself,master - 0 1711522693000 3 connected

新增3690端口的节点，然后setslot,一样报错，比较奇怪
 cluster setslot importing 15be89748bc2aa8f177a32b10656051ce94a60b8 16383
(error) ERR:1,msg:json parse fail

**Comment by wavelet123** [comment]
只配置了requirepass ，没配置masterauth，导致我迁移slot出错，问题已解决，谢谢
