### ISSUE TITLE
centos8.2 make报错

### ISSUE THREAD

**Issue by cheryl-zero** [Tencent/Tendis#269]
### 在x86_64 centos8.2上make报错，gcc (GCC) 8.3.1，cmake version 3.29.3。mkdir build && cd build && cmake ..全部顺利，make -j报错。

报错信息如下：
[ 84%] Built target rocksdb
[ 86%] Built target utils_common
[ 86%] Built target mgl_test
[ 86%] Built target cluster_mgr
[ 86%] Built target record
[ 86%] Built target utils_common_test
[ 86%] Built target skiplist
[ 86%] Built target catalog
[ 86%] Built target record_test
[ 86%] Linking CXX executable ../../../bin/ldb_tendis
[ 86%] Built target rocks_kvstore
[ 86%] Built target rocks_kvstore_for_test
[ 87%] Built target migrate
[ 87%] Built target repl_manager
[ 87%] Building CXX object src/tendisplus/commands/CMakeFiles/commands.dir/command.cpp.o
[ 87%] Building CXX object src/tendisplus/commands/CMakeFiles/commands.dir/kv.cpp.o
[ 87%] Building CXX object src/tendisplus/commands/CMakeFiles/commands.dir/auth.cpp.o
[ 87%] Building CXX object src/tendisplus/commands/CMakeFiles/commands.dir/repl.cpp.o
[ 87%] Building CXX object src/tendisplus/commands/CMakeFiles/commands.dir/cluster.cpp.o
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[2]: *** [src/tendisplus/tools/CMakeFiles/ldb_tendis.dir/build.make:108: bin/ldb_tendis] Error 1
make[1]: *** [CMakeFiles/Makefile2:4742: src/tendisplus/tools/CMakeFiles/ldb_tendis.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

已确认/usr/lib64/中 libdl.so、libpthread.so、libstdc++.so、libm.so、libc.so全部存在。

**Comment by raffertyyu** [comment]
tendisplus仅支持静态链接，考虑执行
```shell
yum install glibc-static libstdc++-static
```
来安装缺少的静态链接库。

**Comment by cheryl-zero** [comment]
已解决，感谢回答！
另外发现链接阶段/tmp中会写入大量内容，make -j6的时候剩余 6.4G 空间但还是提示lto-wrapper: fatal error: write: No space left on device导致链接终止。改成make -j4后不再报错，但过程非常非常缓慢。希望可以优化一下~~
