### ISSUE TITLE
opendb:./db/9, failed info:-ERR:3,msg:IO error: While open a file for appending: ./db/9/2474681.dbtmp: Too many open files

### ISSUE THREAD

**Issue by bdonglobal** [Tencent/Tendis#279]
## Description
tendis目前硬盘用了930G, 本来启动的挺好，有一次发现系统运行异常，检查了一下是tendis启动不了了，机器重新启动了一次也启动不了了，都报相同的错误

## Expected Behavior
tendis能正常启动

## Current Behavior
opendb:./db/9, failed info:-ERR:3,msg:IO error: While open a file for appending: ./db/9/2474681.dbtmp: Too many open files

## Steps to Reproduce (for bugs)
./tendisplus tendis-8903.conf

## Your Environment
tendis-8903.conf:
```
bind 0.0.0.0
port 8903
logdir ./log/
dir ./db
dumpdir ./dump
pidfile ./tendisplus.pid
requirepass "XXX"
masterauth "XXX"
noexpire true
rocks.blockcachemb 9000
cluster-enabled false
maxbinlogkeepnum 50
minbinlogkeepsec 300
binlogDelRange 2
deletefilesinrange-for-binlog true
generallog false
logRecycleThreadnum 1
rocks.max_open_files -1
```

**Comment by raffertyyu** [comment]
可以执行一下`ulimit -a`  看下file descriptors那一行，可以酌情考虑调大这个值。可能是打开文件的个数比较多，被系统限制了。

**Comment by bdonglobal** [comment]
这个值现在是65535，还得继续调大？

**Comment by raffertyyu** [comment]
对，rocksdb会频繁开一些tmp或者log文件，所以我们一般都会设置的比较大。16M左右。

**Comment by bdonglobal** [comment]
好的，改了，改成200000了，竟然启动成功啦，感谢

**Comment by bdonglobal** [comment]
感谢快速comment，问题得以解决
