### ISSUE TITLE
没有   redis冷热混合存储关键组件   相关文档信息

### ISSUE THREAD

**Issue by incubus-ohy** [Tencent/Tendis#28]
如题

**Comment by TendisDev** [comment]
tendis是`冷热混合存储`的关键组件之一，相关文档内容较多，还在整理中

**Comment by dongdongwcpp** [comment]
> tendis是`冷热混合存储`的关键组件之一，混合存储相关文档内容较多，还在整理中

冷热分离存储的redis修改版会开源吗

**Comment by raffertyyu** [comment]
暂时没有开源的计划

**Comment by MollyBa** [comment]
或者 我们自己在tendis上面搭一套redis呢？蛤
