### ISSUE TITLE
pipeline cannot execute successfully "Wrong number of response items from pipeline execution"

### ISSUE THREAD

**Issue by bdonglobal** [Tencent/Tendis#283]
## Description
version:https://github.com/Tencent/Tendis/releases/tag/2.7.0-rocksdb-v8.5.3
pipeline cannot execute successfully "Wrong number of response items from pipeline execution"

## Expected Behavior
pipline execute succeed

## Current Behavior
exception

## Steps to Reproduce (for bugs)
config file:
```
bind 0.0.0.0
port 8903
logdir ./log/
dir ./db
dumpdir ./dump
pidfile ./tendisplus.pid
requirepass "111111"
masterauth "111111"
noexpire true
rocks.blockcachemb 9000
rocks.max_open_files -1
rocks.enable_pipelined_write 1
cluster-enabled false
maxbinlogkeepnum 50
minbinlogkeepsec 300
binlogDelRange 2
deletefilesinrange-for-binlog true
generallog false
logRecycleThreadnum 1
```

the following python script execute failed:
```
with gTendisConn.pipeline() as tendisPip:
            tendisPip.zadd('zs:str:BC','3gif3', '-0.00521694')
            tendisPip.execute()

Wrong number of response items from pipeline execution
```

but I can use the following execute successfully:
```
gTendisConn.zadd('zs:str:BC','3gif3', '-0.00521694')
```

**Comment by bdonglobal** [comment]
this is because pipeline execution result on tendis and redis are different, python did not handle them correctly, the issue has been resolved by updating python redis package's implemenation.

**Comment by sosixyz** [comment]
Which the version of python redis will solve the problem?
