### ISSUE TITLE
info request: RedisSearch compatibility

### ISSUE THREAD

**Issue by Gappa88** [Tencent/Tendis#29]
is Tendis compatible with [RedisSearch](https://oss.redislabs.com/redisearch/)?

thanks

**Comment by TendisDev** [comment]
I don't think so.
Tendis does not support `Redis Modules` yet.

**Comment by xiaming9880** [comment]
希望能快速支持这个特性，确实很需要

**Comment by xiaming9880** [comment]
> I don't think so.
> Tendis does not support `Redis Modules` yet.

有路标吗？大概什么时候可以支撑？

**Comment by raffertyyu** [comment]
暂时没有这方面的需求与计划
