### ISSUE TITLE
Cluster nodes.conf配置支持

### ISSUE THREAD

**Issue by Vegetarianz** [Tencent/Tendis#35]
集群的cluster nodes信息是记录在哪里的呢？实例目录下没有找到相关文件，以及是否支持配置指定

另外，redis cluster支持提前准备好各个实例的nodes.conf文件后，再启动实例，这样可以避免大集群的握手时间。tendis是否支持相同做法

**Comment by TendisDev** [comment]
集群的cluster nodes信息存储在rocksdb中，比使用nodes.conf更为健壮，重启后不需要重新meet
