### ISSUE TITLE
过期删除 和 maxmemory-policy

### ISSUE THREAD

**Issue by wangliguang517** [Tencent/Tendis#39]
1，过期删除
支持文档上提到“对于string的过期，一方面是在get的时候被动删除。另外一方面，会通过compactFilter在commpaction的时候删除掉过期的string”
那什么时候会进行commpaction啊？
2，有maxmemory-policy策略吗？
http://tendis.cn/#/Tendisplus/%E8%BF%90%E7%BB%B4/configuration
看咱们配置参数里没有

**Comment by TendisDev** [comment]
1. compact filter，可参考
https://github.com/facebook/rocksdb/wiki/Compaction-Filter

2. tendis是存储版，不需要maxmemory-policy策略
