### ISSUE TITLE
节点重启速度是否会慢

### ISSUE THREAD

**Issue by wangliguang517** [Tencent/Tendis#40]
在数据量比较大的情况下重启会不会很慢？
假如会比较慢，会有日志打印出来，告诉节点在干什么吗？
PS：这点很重要，否则启动的人，不知道他到底是出问题了，还是正在进行某些工作。

**Comment by TendisDev** [comment]
tendis正常重启拉起速度是很快的

如果是异常重启，有可能需要进入rocksdb的recovery模式，建议看下rocksdb相关文档
https://github.com/facebook/rocksdb/wiki/WAL-Recovery-Modes
会有相关日志
