### ISSUE TITLE
如何使用rename-command 

### ISSUE THREAD

**Issue by valiner** [Tencent/Tendis#42]
![image](https://user-images.githubusercontent.com/17878390/103724952-7fdfbc00-5010-11eb-9046-a2aa9968d2ae.png)

![image](https://user-images.githubusercontent.com/17878390/103724999-984fd680-5010-11eb-8381-bd1a98148b06.png)

使用rename-command ，却提示不存在，tendis集群部署

**Comment by TendisDev** [comment]
rename-command 需要在配置文件中使用，使用方法跟redis一致，可参考
https://redis.io/topics/security
