### ISSUE TITLE
无法写入数据

### ISSUE THREAD

**Issue by valiner** [Tencent/Tendis#44]
![image](https://user-images.githubusercontent.com/17878390/103843464-d6adca00-50d2-11eb-9930-ab16e15983dd.png)
 是在迁移slot后出现的，calc_test_living_detail_num2020-12-2023所在的slot已经迁移成功了

**Comment by TendisDev** [comment]
![image](https://user-images.githubusercontent.com/76082927/103998910-5624c180-51d7-11eb-9a79-8d2350cac03c.png)
建议按照模板提供bug report，描述启动参数，环境，如何重现等关键信息

方便问题定位

**Comment by valiner** [comment]
## Description
无法向tendis集群写入数据，提示 bad entry in block


## Current Behavior
使用hmset 每次向一个key批量写入200个字段，当执行到159200个时，tendis报出异常bad entry in block，此时可以读这个key,但是只要写入这个key就会提示bad entry in block。
scripts/home/log 中的日志显示

E0108 22:17:58.132071 27439 rocks_kvstore.cpp:149] RepllogCursorV2::getMinBinlogId() ERROR: -ERR:3,msg:Result incomplete: Insert failed due to LRU cache being full.
E0108 22:17:58.133412 27439 repl_manager.cpp:791] kvstore->truncateBinlogV2 store:0failed:-ERR:3,msg:RepllogCursorV2 error, detailed at the error log


## Possible Solution
将此配置设置成true，重启可以解决问题
rocks.blockcache_strict_capacity_limit true

## Steps to Reproduce (for bugs)
使用hmset 持续写一个key(几率性发生)


## Your Environment
* Operating System and version: CentOS7.8
* Machine Specifications:  4c8g
* Tendis Version: tendis-2.1.2-rocksdb-v5.13.4
* Tendis Configuration:

bind 172.16.0.131
loglevel notice
cluster-enabled yes
logdir ./home/log
dumpdir ./home/dump
dir ./home/db
pidfile ./home/tendisplus.pid
slowlog ./home/log/slowlog
rocks.blockcachemb 3096
rocks.blockcache_strict_capacity_limit true
netiothreadnum 4
executorThreadNum 6
minbinlogkeepsec 86400
maxbinlogkeepnum 30

**Comment by TendisDev** [comment]
每个field的size是多大？

更具体的操作方法建议通过命令的方式发下

**Comment by TendisDev** [comment]
这个问题的原因是
`rocks.blockcache_strict_capacity_limit true`
导致的，如果内存比较小，不建议指定该参数为true

新版本会考虑去掉这个参数
