### ISSUE TITLE
和pika比较有什么优势呢

### ISSUE THREAD

**Issue by cossbow** [Tencent/Tendis#5]
和pika比较有什么优势呢

**Comment by TendisDev** [comment]
可在文档中对比一下

tendis存储版-vs-其他开源实现
http://tendis.cn/#/Tendisplus/%E6%95%B4%E4%BD%93%E4%BB%8B%E7%BB%8D/%E5%AF%B9%E6%AF%94?id=tendis%e5%ad%98%e5%82%a8%e7%89%88-vs-%e5%85%b6%e4%bb%96%e5%bc%80%e6%ba%90%e5%ae%9e%e7%8e%b0

命令兼容性，tendis支持更全面的redis指令，并且保证redis语义，同时支持原生的cluster模式
tendis: http://tendis.cn/#/Tendisplus/%E6%95%B4%E4%BD%93%E4%BB%8B%E7%BB%8D/redis%E5%85%BC%E5%AE%B9%E6%80%A7
pika: https://github.com/Qihoo360/pika/wiki/pika-%E6%94%AF%E6%8C%81%E7%9A%84redis%E6%8E%A5%E5%8F%A3%E5%8F%8A%E5%85%BC%E5%AE%B9%E6%83%85%E5%86%B5


性能对比
tendis: http://tendis.cn/#/Tendisplus/%E6%95%B4%E4%BD%93%E4%BB%8B%E7%BB%8D/%E6%80%A7%E8%83%BD%E6%8A%A5%E5%91%8A
pika: https://github.com/Qihoo360/pika/wiki/3.2.x-Performance
