### ISSUE TITLE
cmake failed 

### ISSUE THREAD

**Issue by wuhongda** [Tencent/Tendis#54]
CMake Error: install(EXPORT "glog-targets" ...) includes target "glog" which requires target "gflags_nothreads_static" that is not in the export set.
CMake Error: install(EXPORT "RocksDBTargets" ...) includes target "rocksdb" which requires target "gflags_nothreads_static" that is not in the export set.
CMake Error: install(EXPORT "RocksDBTargets" ...) includes target "rocksdb-shared" which requires target "gflags_nothreads_static" that is not in the export set.
-- Generating done

**Comment by TendisDev** [comment]
Duplicate of #9

**Comment by TendisDev** [comment]
已解决
