### ISSUE TITLE
配置文件如何生效

### ISSUE THREAD

**Issue by linzhiming0826** [Tencent/Tendis#56]
使用docker-compose部署，编辑tendisplus.conf,重启服务docker-compose restart，观察tendisplus.conf，刚刚配置的信息已经被还原了

**Comment by OMG-By** [comment]
docker-compose reset 命令是docker容器层面的命令。大概流程是会根据yaml配置文件重新拉取和编排。所以reset后会重启容器内的所有配置。
如果需要使修改tendisplus.conf的操作生效。建议容器内重启tendisplus程序。
这边考虑更新一下docker-compose。对用户暴露tendisplus.conf模板，用户可在模板上进行参数修改。启动时，使用用户指定配置。

**Comment by linzhiming0826** [comment]
version: '3'
services:
  tendisplus-master-0:
    image: tencentdbforkv/tendisplus:latest
    container_name: tendisplus-master-0
    ports:
      - "30000:51002"
    networks:
      tendisplus-net:
        ipv4_address: 192.168.98.10
    environment:
      - REDIS_PASSWORD=11111
      - CLUSTER=no
    volumes:
      - "/data/tendis/30000:/data1/tendis/51002"
    restart: on-failure:3
    logging:
      driver: "json-file"
      options:
        max-size: "500m"

networks:
  tendisplus-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.98.0/24

你好，这个是我的compose的配置，对外是挂载了/data1/tendis/51002 这一整个目录，我修改的就是data/tendis/3000目录下/的配置文件tendisplus.conf，我尝试了docker restart 与docker-compose restart ,配置文件都会被还原，所以对用户暴露的tendisplus.conf模板，是应该以怎么样的一个正确方式去暴露

**Comment by OMG-By** [comment]
这涉及到容器拉起时，start.sh启动进程的脚本行为。每次会cp模板文件到对应目录，所以会覆盖到你修改过的配置。
该脚本位于容器/data1/tendis/scripts目录下。(tendisplus模板文件也在该目录下)

**Comment by linzhiming0826** [comment]
多谢，已经解决配置文件问题
