### ISSUE TITLE
Tendis

### ISSUE THREAD

**Issue by wuhongda** [Tencent/Tendis#58]
1、Tendis-cluster支持读写分离吗？
2、有没有官方的交流群呢？

**Comment by cnzoupeng** [comment]
http://tendis.cn/#/ 这里有QQ群二维码

**Comment by liyangbing** [comment]
> http://tendis.cn/#/ 这里有QQ群二维码

可以有个微信群吗？

**Comment by MollyBa** [comment]
> 



> 1、Tendis-cluster支持读写分离吗？ 2、有没有官方的交流群呢？

所以支持读写分离吗？ 目前测试的结果 读接受到请求也是redic到key所属槽的matser上
