### ISSUE TITLE
使用binlog_tool以base64格式分析日志文件时，并没有输出结尾的read logfile end

### ISSUE THREAD

**Issue by AlbertGithubHome** [Tencent/Tendis#59]
## Description
http://tendis.cn/#/Tendisplus/%E8%BF%90%E7%BB%B4/backup?id=binlog_tool
参照文档进行测试时，使用binlog_tool以base64格式分析日志文件，并没有输出结尾的read logfile end

## Expected Behavior
按照文档形式输出

## Current Behavior
没有结尾内容
```
$ ../../../../bin/binlog_tool --logfile=binlog-5-0000004-20210118153530.log --mode=base64
restorebinlogv2 5 ////Af////8BAAAAAAAAAAMAAAgA /wAAAAAAAAAAPIcAAwAAAAAAAAA/AAABdxRztq///////////wRpbmNyAa/tzqPxLg4AADyHRAAAAABhAAABAAhhAAAAAAAAMw==
restorebinlogv2 5 ////Af////8BAAAAAAAAAAQAAAgA /wAAAAAAAAAAPIcAAwAAAAAAAABNAAABdxRz4qL//////////wNzZXQBosXPo/EuDgAAPIdEAAAAAGEAAAEACGEAAAAAAAAx
restorebinlogv2 5 ////Af////8BAAAAAAAAAAUAAAgA /wAAAAAAAAAAPIcAAwAAAAAAAABTAAABdxRz8eL//////////wRpbmNyAeLjz6PxLg4AADyHRAAAAABhAAABAAhhAAAAAAAAMg==
```
## Your Environment
- Ubuntu 16.04 
- 下载的最新[release包](https://github.com/Tencent/Tendis/releases/tag/2.1.2-rocksdb-v5.13.4)
- binlog文件已添加到附件
[binlog-5-0000004-20210118153530.log](https://github.com/Tencent/Tendis/files/5830220/binlog-5-0000004-20210118153530.log)

**Comment by Evil-crow** [comment]
此处是正常的行为.最早的设计是考虑结束串来表意EOF
`binlog_tool`**仅仅用来进行日志输出.日志是否完整并不能进行保证**.需要通过其他方式确认
所以此处,移除了`read logfile end`
可以通过脚本将行为组合起来. 经由管道直接将导出的binlog进行处理.无需特殊处理结束串
详情可见[代码>>>](https://github.com/Tencent/Tendis/blob/15f78295dbf0be6c57d06d70ae7b6119ee53344d/src/tendisplus/replication/binlog_tool.cpp#L107)

**Comment by AlbertGithubHome** [comment]
> 此处是正常的行为.最早的设计是考虑结束串来表意EOF
> `binlog_tool`**仅仅用来进行日志输出.日志是否完整并不能进行保证**.需要通过其他方式确认
> 所以此处,移除了`read logfile end`
> 可以通过脚本将行为组合起来. 经由管道直接将导出的binlog进行处理.无需特殊处理结束串
> 详情可见[代码>>>](https://github.com/Tencent/Tendis/blob/15f78295dbf0be6c57d06d70ae7b6119ee53344d/src/tendisplus/replication/binlog_tool.cpp#L107)

感谢回复，希望能及时更新文档内容
