### ISSUE TITLE
是否支持KEEPTTL

### ISSUE THREAD

**Issue by OptimusV5** [Tencent/Tendis#64]
## Description
redis 6.0的SET命令引入了KEEPTTL的选项，想问下Tendis支持这个么？没有看到相关文档

## Expected Behavior

redis> SET greeting "hello world" EX 100
OK
redis> TTL greeting
(integer) 99
redis> SET greeting "hello redis" KEEPTTL
OK
redis> TTL greeting
(integer) 97

**Comment by TendisDev** [comment]
目前还没支持redis 6.0的功能和语法，后续会排期支持
如果有紧急需要，也建议大家提PR来实现一下
