### ISSUE TITLE
tendisplus对于过期数据是如何处理的

### ISSUE THREAD

**Issue by zhaochunxue** [Tencent/Tendis#68]
过期的数据,会自动清理吗?还是要通过手动的compact才会清理过期的数据

**Comment by TendisDev** [comment]
会自动清理，不需要手动的

**Comment by zhaochunxue** [comment]
> 会自动清理，不需要手动的

清理机制是什么样的,有文档说明吗?

**Comment by flywukong** [comment]
参考官方文档的 过期key索引部分， 总体来说KV类型是通过rockdb自身的CompactionFilter做删除的， 其它的类型是通过后台线程池删除
