### ISSUE TITLE
tendisplus的官方镜像

### ISSUE THREAD

**Issue by zhaochunxue** [Tencent/Tendis#69]
毕竟现在使用容器部署的人越来越多,这应该也是基础建设的一部分,我们目前就是使用容器部署的,不知道下一版优化的官方镜像什么时候出

**Comment by OMG-By** [comment]
您所指的优化是什么？能具体例出要求吗？
容器的laster会随tendisplus相应更新，并保留各个版本的tag，提供给用户指定拉取。

PS：容器部署只为了用户可快速体验，并不建议用于生产环境。所以会有很多配置上没那么严谨。
