### ISSUE TITLE
可以平滑替换项目中的redis吗

### ISSUE THREAD

**Issue by 121417** [Tencent/Tendis#7]

**Comment by Evil-crow** [comment]
先说结论: 可以的

**Comment by Evil-crow** [comment]
先说结论: 可以的
`Tendis存储版`支持兼容Redis协议.并且提供扩展能力.可以参考以下文档:
1. [使用限制](http://tendis.cn/#/Tendisplus/%E6%95%B4%E4%BD%93%E4%BB%8B%E7%BB%8D/%E4%BD%BF%E7%94%A8%E9%99%90%E5%88%B6)
2. [从Redis迁移到Tendis存储版](http://tendis.cn/#/Tendisplus/%E7%9F%A5%E8%AF%86%E5%BA%93/%E6%95%B0%E6%8D%AE%E8%BF%81%E7%A7%BB/redis_migrate_to_tendis%E5%AD%98%E5%82%A8%E7%89%88)

需要注意: **目前我们验证通过Redis4.x迁移, 其他版本有待验证**, 如有问题, 欢迎issue和PR. (迁移工具在文档页提供二进制链接)
