### ISSUE TITLE
重启tendis报错！

### ISSUE THREAD

**Issue by meixiaolong** [Tencent/Tendis#71]
部署单机版tendis直接kill pid后启动，报如下错误：
E0209 10:00:48.711889 24107 record.cpp:176] invalid rcdchr:0
E0209 10:00:48.712033 24107 record.cpp:178] INVARIANT failed:0 /data/tendis_bin/workspace/tendisplus-master-release/pipeline_248/tendisplus/src/tendisplus/storage/record.cpp 178
E0209 10:00:48.712044 24107 record.cpp:110] INVARIANT failed:0 /data/tendis_bin/workspace/tendisplus-master-release/pipeline_248/tendisplus/src/tendisplus/storage/record.cpp 110
F0209 10:00:48.712051 24107 record.cpp:111] invalid recordtype:0

把home/dump目录清空后启动正常。

**Comment by meixiaolong** [comment]
有关binlog的三个参数：

truncateBinlogIntervalMs 100
truncateBinlogNum 50000
binlogDelRange 50000

**Comment by TendisDev** [comment]
先将配置改为
binlogDelRange 1

这个是一个bug，已修复，下个版本发布
