### ISSUE TITLE
macos编译失败

### ISSUE THREAD

**Issue by jonnywang** [Tencent/Tendis#72]
#define TENDISPLUS_GIT_SHA1 "5168aae3"
#define TENDISPLUS_GIT_DIRTY "      17"
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CMake Error at CMakeLists.txt:35 (message):
  gcc or vs2015(update 2)+ is required

gcc本地brew方式已经
gcc (Homebrew GCC 10.2.0_4) 10.2.0

求解决方式

**Comment by Evil-crow** [comment]
`gcc`版本过高,对于目前`Tendis`依赖的`RocksDB`版本而言不适用.
且在`MacOS`上可能存在本地库不兼容的问题.`Tendis`目前不保证在`MacOS`上编译通过
目前测试编译通过`gcc-5.5.0`,`gcc-7.3.0`, `gcc-7.5.0`
请尝试使用`Linux`平台下, 进行编译测试或直接使用`Release`的二进制文件.

**Comment by jonnywang** [comment]
感谢，看来mac试用不了哦
