### ISSUE TITLE
Tendis官方社区交流群，入群验证问题的答案是什么呀？

### ISSUE THREAD

**Issue by kenlee1988** [Tencent/Tendis#74]
Tendis官方社区交流群，入群问题的答案是什么呀？
试了很多次，都是答案错误

**Comment by huawux** [comment]
请重新加群，谢谢反馈。

**Comment by piaoairy219** [comment]
得填“是”，是的，匹配，完全匹配...都不能通过:)

**Comment by kenlee1988** [comment]
谢谢，我试了很多次都不行，主要它的问题是“Tendis兼容redis协议吗？”我就回答，兼容，完全兼容等等。。。
