### ISSUE TITLE
docker单容器启动失败

### ISSUE THREAD

**Issue by EpicArena** [Tencent/Tendis#78]
## 运行方式
docker run -itd -p 51002:51002 tencentdbforkv/tendisplus

## docker错误输出
start.sh: line 26:    27 Illegal instruction     ../bin/tendisplus ${dir}/${port}/tendisplus.conf

## 镜像版本
tencentdbforkv/tendisplus:latest
v2.1.3、v2.2.1试了也不行

**Comment by OMG-By** [comment]
这个测试执行是可以的。
看报错像是启动脚本中的 ${dir}和${port}未定义，这两个变量在单容器版中是定义在脚本中的。
麻烦使用docker logs 看下具体输出了什么。

**Comment by OMG-By** [comment]
经过初步沟通排查，怀疑是机器不支持avx指令集或者是否是docker的安装出现的问题

**Comment by TendisDev** [comment]
Duplicate of #50

**Comment by EpicArena** [comment]
情形不太一样，我用源码编译是可以运行的，并没有报错，但是docker运行就不可以

**Comment by TendisDev** [comment]
由于指令集不一样，编译的二进制包使用了你的机器不支持的CPU指令集，所以docker运行不正常，但自己编译的却可以。

您可以自己编译后构建一个docker镜像
