### ISSUE TITLE
Parallel Occ chk

### ISSUE THREAD

**Issue by wolfkdy** [Tencent/Tendis#8]
it is suggested that tendisplus upgrades to rocks 6.x series.  Or backport [this patch](https://github.com/facebook/rocksdb/pull/6240).
As tendisplus uses rocksdb's occ. It may suffer great lock contentions on serializely commit chk.
By upgrading to parallel occ, pure in-mem workload should gain 4x better performance.

**Comment by TendisDev** [comment]
Good suggestions.
There are plans to upgrade the rocksdb to 6.x in next release.

Currently, tendis use pess txn as default. And we would also check other features in new rocks.

Thanks, deyu. Including all contributions to tendis.

**Comment by raffertyyu** [comment]
Tendisplus 2.5.0 has upgraded rocksdb to 6.23.3.
Thanks for contributions.
