### ISSUE TITLE
tendis 编译报错 -- JNI library is disabled  /usr/bin/ld: cannot find -lpthreads

### ISSUE THREAD

**Issue by jimking0301** [Tencent/Tendis#82]
如题x86_64环境，centos7系统，cmake和java版本如下图
![image](https://user-images.githubusercontent.com/80300917/110731690-c4304800-825d-11eb-8076-0429b5171df3.png)

在使用cmake编译是提示报错-- JNI library is disabled，如下图
![image](https://user-images.githubusercontent.com/80300917/110731758-ee820580-825d-11eb-85a7-0ec00812758d.png)

查看CMakeError.log中提示报错/usr/bin/ld: cannot find -lpthreads，如下图
![image](https://user-images.githubusercontent.com/80300917/110731863-0ce80100-825e-11eb-92bb-061f1d82372e.png)

请问应该如何排查

**Comment by TendisDev** [comment]
Duplicate of #16

**Comment by TendisDev** [comment]
可参考 issue #16

**Comment by TendisDev** [comment]
已解决，clone最新代码试试
