### ISSUE TITLE
with NEW_ROCKSDB=ON, ldb_tendis link fail

### ISSUE THREAD

**Issue by xuning97** [Tencent/Tendis#85]
## Description
`
[100%] Linking CXX executable ../../../bin/ldb_tendis
cd /work/Tendis/build/src/tendisplus/tools && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/ldb_tendis.dir/link.txt --verbose=1
ccache /usr/bin/c++  -std=c++17 -g -fno-omit-frame-pointer  -O2 -Wall -Wextra -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-float-equal -Wendif-labels -Wfloat-equal -Wformat=2 -Wframe-larger-than=69632 -Wmissing-include-dirs -Wpointer-arith -Wwrite-strings -Werror=char-subscripts -Werror=comments -Werror=conversion-null -Werror=empty-body -Werror=endif-labels -Werror=format -Werror=format-nonliteral -Werror=missing-include-dirs -Werror=overflow -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=sign-compare -Werror=switch -Werror=type-limits -Werror=uninitialized -Wno-maybe-uninitialized -Werror=unused-function -Werror=unused-label -Werror=unused-result -Werror=unused-value -Werror=unused-variable -Werror=write-strings -Wno-invalid-offsetof -Wno-format-truncation -Wnon-virtual-dtor -Woverloaded-virtual -Wvla -Werror=non-virtual-dtor -Werror=overloaded-virtual -Werror=vla -O2 -g -DNDEBUG CMakeFiles/ldb_tendis.dir/ldb.cc.o CMakeFiles/ldb_tendis.dir/ldb_cmd.cc.o CMakeFiles/ldb_tendis.dir/ldb_tool.cc.o -o ../../../bin/ldb_tendis   -L/work/Tendis/src/thirdparty/jemalloc/lib  -Wl,-rpath,/work/Tendis/src/thirdparty/jemalloc/lib ../../../lib/libutils_common.a ../../../lib/libkvstore.a ../../../lib/librecord.a ../../../lib/librocksdb.a ../../../lib/libglog.a ../../../../src/thirdparty/jemalloc/lib/libjemalloc_pic.a -ldl -lpthread -lrt ../../../lib/libsync_point.a ../../../lib/libsnappy.a -static -static-libgcc -static-libstdc++ -Wl,--no-as-needed -ldl -pthread -mno-avx -mno-avx2 -lstdc++fs ../../../lib/libutils_common.a ../../../lib/libvarint.a ../../../lib/libstatus.a ../../../lib/libglog.a ../../../lib/liblz4.a ../../../../src/thirdparty/jemalloc/lib/libjemalloc.so -lpthread
/usr/bin/ld: 试图静态链结的动态对象 ../../../../src/thirdparty/jemalloc/lib/libjemalloc.so
collect2: 错误：ld 返回 1
`

* Tendis Version: dev-2.2

**Comment by jingjunLi** [comment]
Thanks for advices, now you can change src/tendisplus/tools/CMakeLists.txt, delete `-static -static-libgcc -static-libstdc++` flags, later we will fix the problem.

**Comment by TendisDev** [comment]
The compile problem has been fixed. Please checkout the latest version.
