### ISSUE TITLE
Cannot Start Tendis as a Cluster

### ISSUE THREAD

**Issue by marswong** [Tencent/Tendis#86]
## Description
just follow the official [doc](https://tendis.cn/#/Tendisplus/%E8%BF%90%E7%BB%B4/new_cluster), but only one process is created.

## Expected Behavior
it'd create 6 process

## Current Behavior
just create one process and error occured.

## Steps to Reproduce (for bugs)
just follow the doc:

```
./bin/tendisplus ./tendis.conf.30000
./bin/tendisplus ./tendis.conf.30001
./bin/tendisplus ./tendis.conf.30002
./bin/tendisplus ./tendis.conf.30003
./bin/tendisplus ./tendis.conf.30004
./bin/tendisplus ./tendis.conf.30005
```

## Context

tendis.conf.30000:

```
cluster-enabled true
bind 127.0.0.1
port 30000
pidfile ./tendisplus-0.pid
```

tendis.conf.30001:

```
cluster-enabled true
bind 127.0.0.1
port 30001
pidfile ./tendisplus-1.pid
```

tendis.conf.30002:

```
cluster-enabled true
bind 127.0.0.1
port 30002
pidfile ./tendisplus-2.pid
```

tendis.conf.30003:

```
cluster-enabled true
bind 127.0.0.1
port 30003
pidfile ./tendisplus-3.pid
```

tendis.conf.30004:

```
cluster-enabled true
bind 127.0.0.1
port 30004
pidfile ./tendisplus-4.pid
```

tendis.conf.30005:

```
cluster-enabled true
bind 127.0.0.1
port 30005
pidfile ./tendisplus-5.pid
```

tendisplus.ERROR:

```
Lsog file created at: 2021/03/15 15:39:52
Running on machine: tendis-debian-m-8vcpu-64gb-sfo2-01
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0315 15:39:52.495764  3000 rocks_kvstore.cpp:1878] opendb:./db/catalog, failed info:-ERR:3,msg:IO error: While lock file: ./db/catalog/LOCK: Resource temporarily unavailable
```

## Your Environment
* Operating System and version: Debian 9
* Machine Specifications: DigitalOcean's Memory-Optimized droplet with 8 core and 64g
* Tendis Version: 2.2.2-rocksdb-v5.13.4

**Comment by TendisDev** [comment]
Please add necessary configuration such as data and log directory(`dir`, `logdir`). 
For exmaple,
```
pidfile ./home/tendisplus.pid
logdir ./home/log
dir ./home/db
dumpdir ./home/dump
```

And each process uses a different directory, more detail:
https://tendis.cn/#/Tendisplus/%E8%BF%90%E7%BB%B4/conf_templ

**Comment by marswong** [comment]
@TendisDev Thank you. some advices:

1. use convention instead of configuration, or it'd be hard to begin
2. update the broken doc.

**Comment by TendisDev** [comment]
Thanks for advices, we should update the document.
