### ISSUE TITLE
编译cmake..报错：已经成功安装过gflags

### ISSUE THREAD

**Issue by zhuqiuxia** [Tencent/Tendis#9]
CMake Error at /usr/local/lib/cmake/gflags/gflags-nonamespace-targets.cmake:34 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: gflags_nothreads_static

  Targets not yet defined:
  gflags_shared;gflags_nothreads_shared;gflags_static

Call Stack (most recent call first):
  /usr/local/lib/cmake/gflags/gflags-config.cmake:17 (include)
  src/thirdparty/snappy/CMakeLists.txt:133 (find_package)

**Comment by TendisDev** [comment]
可以尝试删除本地gflags 或者
安装gflags_shared;gflags_nothreads_shared;gflags_static后
再编译

**Comment by zhuqiuxia** [comment]
删除gflags安装之后，报错：
CMake Warning at src/thirdparty/rocksdb-5.13.4/rocksdb/CMakeLists.txt:75 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" with any
  of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by zhuqiuxia** [comment]
现在编译通过了，make 报错：
Scanning dependencies of target time_util
Scanning dependencies of target sync_point
[  6%] Building CXX object src/tendisplus/utils/CMakeFiles/time_util.dir/time.cpp.o
[  6%] Linking CXX executable ../../../../bin/simplewriter
[  6%] Building CXX object src/tendisplus/utils/CMakeFiles/sync_point.dir/sync_point.cpp.o
g++: fatal error: no input files
compilation terminated.
[  6%] Linking CXX static library ../../../lib/libgflags_nothreads.a
/bin/sh: -lgflags: command not found
make[2]: *** [src/tendisplus/utils/CMakeFiles/time_util.dir/time.cpp.o] Error 127
make[1]: *** [src/tendisplus/utils/CMakeFiles/time_util.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
g++: fatal error: no input files
compilation terminated.
/bin/sh: -lgflags: command not found
make[2]: *** [src/tendisplus/utils/CMakeFiles/sync_point.dir/sync_point.cpp.o] Error 127
make[1]: *** [src/tendisplus/utils/CMakeFiles/sync_point.dir/all] Error 2
[  6%] Linking CXX executable ../../../../bin/serialize
[  6%] Built target simplewriter
[  6%] Built target gflags_nothreads_static
[  6%] Built target serialize
[  6%] Linking CXX executable ../../../../bin/simpledom
[  6%] Built target simpledom
[  6%] Linking CXX executable ../../../../bin/simplepullreader
[  6%] Built target simplepullreader
[  6%] Linking CXX executable ../../../../bin/parsebyparts
[  6%] Built target parsebyparts
[  6%] Linking CXX executable ../../../../bin/sortkeys
[  6%] Built target sortkeys
[  6%] Linking CXX executable ../../../../bin/schemavalidator
[  6%] Built target schemavalidator
[  6%] Linking CXX static library ../../../../lib/libgtest.a
[  6%] Built target gtest
[  6%] Linking CXX static library ../../../../../../../../lib/libgtest_rocks.a
[  6%] Built target gtest_rocks
make: *** [all] Error 2

**Comment by zhengyouxiang** [comment]
我也出現了 你怎麼解決的

**Comment by jingjunLi** [comment]
这个原因主要是由于系统已安装的 gflags 编译安装时没有使用指定 -fPIC 编译选项(`cmake ..  -DCMAKE_CXX_FLAGS=-fPIC`) , 你可以删除系统安装的 gflags (rm /usr/local/lib/cmake/gflags), 然后将 build 目录删除, 再重新编译试一下。

**Comment by TendisDev** [comment]
已解决，请更新最新的代码
