### ISSUE TITLE
sessid:16718 cmd:binlog_heartbeat 2 1617101832885, error:-ERR:6,msg:sessionId not match

### ISSUE THREAD

**Issue by zhaochunxue** [Tencent/Tendis#90]
3.31号一个从节点报出来了好多上边的问题,不知道这些日志代表什么,只能大概的知道是主从同步有问题,还希望官方能给出解释和优化
![image](https://user-images.githubusercontent.com/64675999/113232246-53fe6a80-92cf-11eb-9fe7-2c22a22be83d.png)

**Comment by TendisDev** [comment]
“sessionId not match” 的意思是
在10秒内，slave没有收到master的binlog，会重新建立一个session进行拉取binlog。但如果此时原来的session恢复，但由于不允许多个session接收binlog，原来的session执行时候就会报错“sessionId not match”

出现这个错误一般以下原因：
1. 主备时间短暂网络异常
2. master异常，心跳binlog没有正常产生
3. master hang住，并超过10s

这个需要重现并按现场分析其原因

**Comment by zhaochunxue** [comment]
> “sessionId not match” 的意思是
> 在10秒内，slave没有收到master的binlog，会重新建立一个session进行拉取binlog。但如果此时原来的session恢复，但由于不允许多个session接收binlog，原来的session执行时候就会报错“sessionId not match”
> 
> 出现这个错误一般以下原因：
> 
> 1. 主备时间短暂网络异常
> 2. master异常，心跳binlog没有正常产生
> 3. master hang住，并超过10s
> 
> 这个需要重现并按现场分析其原因

上边日志里边报出来的heartbeat报出来的异常不是你说的第二种吗? 如果不是的话,可能要先找到我问的第一个问题https://github.com/Tencent/Tendis/issues/89

**Comment by TendisDev** [comment]
> > “sessionId not match” 的意思是
> > 在10秒内，slave没有收到master的binlog，会重新建立一个session进行拉取binlog。但如果此时原来的session恢复，但由于不允许多个session接收binlog，原来的session执行时候就会报错“sessionId not match”
> > 出现这个错误一般以下原因：
> > 
> > 1. 主备时间短暂网络异常
> > 2. master异常，心跳binlog没有正常产生
> > 3. master hang住，并超过10s
> > 
> > 这个需要重现并按现场分析其原因
> 
> 上边日志里边报出来的heartbeat报出来的异常不是你说的第二种吗? 如果不是的话,可能要先找到我问的第一个问题#89

也不一定，也可能是心跳binlog产生了，但只是没发过来，或者堵在网络上

**Comment by TendisDev** [comment]
另外，你的版本是什么？后面请按照模版提交下issue，可以加快沟通效率

**Comment by zhaochunxue** [comment]
> 另外，你的版本是什么？后面请按照模版提交下issue，可以加快沟通效率

是你们最新发布的版本,2.2.2
![image](https://user-images.githubusercontent.com/64675999/113373300-1f58e480-939d-11eb-9ef9-5cd249157603.png)

**Comment by zhaochunxue** [comment]
> 另外，你的版本是什么？后面请按照模版提交下issue，可以加快沟通效率

对于我上边的问题,有没有什么调优的配置呢
