### ISSUE TITLE
tencentdbforkv/tendisplus:v2.2.2  及2.2.3版本  db中.log文件存储信息会存储2份key:value？

### ISSUE THREAD

**Issue by covered** [Tencent/Tendis#92]
版本：docker-compose   tencentdbforkv/tendisplus:v2.2.2  及2.2.3

执行set命令：set ddd:aaa "0123456789" （仅1次）
数据目录：tendis/data/db/0/000003.log
数据文件内容（base64后）：
IGPNeD8AAQEAAAAAAAAAAgAAAA0KARQAABc6RAAAAABkZGQ6YWFhAAAHABNhAAAA
AAAAIjAxMjM0NTY3ODkiBQEV////Af////8BAAAAAAAAAAEAAAgAWf8AAAAAAAAA
ABc6AAMAAAAAAAAAAgAAAXiw6GB8//////////8DU0VUAfzAoYc/FAAAFzpEAAAA
AGRkZDphYWEAAAcAE2EAAAAAAAAiMDEyMzQ1Njc4OSI=
解码base64后可见 2份key:value存储

一次执行set 数据文件中 可见2组 key与value ？这是正常存储机制吗？大量数据实测库文件大小大约为实际value大小的2倍多。
数据格式文档中未见提及2份存储。
http://tendis.cn/#/Tendisplus/%E7%9F%A5%E8%AF%86%E5%BA%93/%E5%AD%98%E5%82%A8%E6%A0%BC%E5%BC%8F/record_format

配置：
port 51002
bind 172.30.0.5
loglevel debug
logdir /data1/tendis/data/log
dumpdir /data1/tendis/data/dump
dir /data1/tendis/data/db
pidfile /data1/tendis/data/tendisplus.pid
slowlog /data1/tendis/data/log/slowlog
storage rocks
#全量日志，日志限制未测试
generallog 0
checkkeytypeforsetcmd false
noexpire 1

#binlog设置 binlogDelRange：到达此设置时批量删除 集群时需要调整。num为条数？
maxBinlogKeepNum 1
minBinlogKeepSec 0
truncateBinlogIntervalMs 5000
truncateBinlogNum 1
binlogDelRange 1
binlogFileSizeMB 64
binlogFileSecs 2060

#rocksdb 数据库个数相关
kvStoreCount 1

executorThreadNum 8

#keys查询限制
keysDefaultLimit 200
scanDefaultLimit 10
scanDefaultMaxIterateTimes 100
cluster-enabled no

requirepass test
masterauth test

#严格限制内存，具体影响待测试
rocks.blockcache_strict_capacity_limit 1

#调大可以在key很多时节约内存 block_cache  https://kernelmaker.github.io/Zeppelin-rocksdb-options
#与cache_index_and_filter_blocks配合使用，开启时不占内存，不开启则 block在内存中
rocks.blockcachemb 64
rocks.cache_index_and_filter_blocks 1
rocks.optimize_filters_for_hits 1

#启用压缩
rocks.compress_type lz4
rocks.level1_compress_enabled yes

#云盘优化 write_buffer_size越小，高速写入时占用内存越少。相关配置 max_write_buffer_number min_write_buffer_number_to_merge
rocks.write_buffer_size 16777216
rocks.max_background_flushes 2
rocks.max_write_buffer_number 4
rocks.min_write_buffer_number_to_merge 2
rocks.max_background_compactions 2
rocks.level0_slowdown_writes_trigger 5

rocks.target_file_size_base 134217728
rocks.max_bytes_for_level_base 536870912
rocks.level_compaction_dynamic_level_bytes 0

**Comment by TendisDev** [comment]
一条数据，一条是binlog
binlog目前用于主备同步以及数据迁移

**Comment by covered** [comment]
> 一条数据，一条是binlog
> binlog目前用于主备同步以及数据迁移

单机使用时可以关闭binlog存储吗

**Comment by TendisDev** [comment]
> > 一条数据，一条是binlog
> > binlog目前用于主备同步以及数据迁移
> 
> 单机使用时可以关闭binlog存储吗

slave也不需要？
目前不支持关闭
