### ISSUE TITLE
slot迁移慢

### ISSUE THREAD

**Issue by zhaochunxue** [Tencent/Tendis#94]
这个tendisplus2.2.2版本迁移slot，除了这几个参数外还有别的影响参数吗？我现在的配置是下边4个参数的配置
cluster-migration-rate-limit这个参数代表的是32M/s吗？按照下边的配置，目前迁移1小时只能迁移1.5G的数据
migratereceivethreadnum 4
migratesenderthreadnum 4
cluster-migration-rate-limit 32
cluster-migration-slots-num-per-task 10

**Comment by flywukong** [comment]
是的，32这个值可以调到200M试试， cluster-migration-slots-num-per-task适度增大也可以增加搬迁速度，其它参数对搬迁速度没影响，我们下一个版本会对搬迁效率 有一些优化

**Comment by zhaochunxue** [comment]
> 是的，32这个值可以调到200M试试， cluster-migration-slots-num-per-task适度增大也可以增加搬迁速度，其它参数对搬迁速度没影响，我们下一个版本会对搬迁效率 有一些优化

参数调整为以下两个值,变化不是很明显
cluster-migration-rate-limit 500
cluster-migration-slots-num-per-task 15
![image](https://user-images.githubusercontent.com/64675999/114484578-1093ec80-9c3d-11eb-87bc-12497d17c163.png)
