### ISSUE TITLE
如何限制binlog数目，有一个db已经写了3千多个文件了

### ISSUE THREAD

**Issue by dneht** [Tencent/Tendis#97]
有一台机器的db5已经230g+了，文件从0000到binlog-5-0003173-20210416191838.log

请教一下何时或者说如何清理binlog

和binlog相关只配置了这四项，其他都是默认值，3master节点的集群，无slave

版本：2.2.2-rocksdb-v5.13.4

```
maxbinlogkeepnum 100
minbinlogkeepsec 0
truncateBinlogIntervalMs 5000
truncateBinlogNum 100
```

**Comment by TendisDev** [comment]
现在可以通过后台脚本去定时删除

后面新版本会新增一个参数，不再导出binlog
