### ISSUE TITLE
Any plan to maintain official docker images?

### ISSUE THREAD

**Issue by huanggx-sea** [Tencent/Tendis#98]
## Description
Currently seems like there're just third party `tendis` image repo on [docker hub](https://hub.docker.com/search?q=tendis&type=image). Do you have any plan to maintain a official docker image repo?

## Expected Behavior
None

## Current Behavior
None

## Possible Solution

- Maintain a Dockerfile in this repo and publish latest release in [Docker Hub](https://hub.docker.com)

## Context
It would be much eaiser to use `tendis` in Kubernetes if we can just download official images directly.

**Comment by huanggx-sea** [comment]
Found https://hub.docker.com/r/tencentdbforkv/tendisplus

**Comment by vincentmele** [comment]
I've created a separate repo that should provide a configurable base for building Tendis for use in Kubernetes. https://github.com/nyseion/tendis-docker
